-- dcs-sms framework: countries module (sms.countries).
--
-- Hand-maintained enum of DCS country.id keys. Mission code uses
-- sms.countries.<KEY> instead of magic strings:
--
--     sms.group.create({country = sms.countries.USA, ...})
--     sms.static.create({country = sms.countries.RUSSIA, ...})
--
-- Values are the upper-snake form that country.id itself uses, which
-- gives the invariant sms.countries.X == "X". sms.utils.resolve_country
-- accepts either the upper-snake form or display variants ("USA",
-- "usa", "United Kingdom"); the enum picks the canonical form.
--
-- Runtime drift check (bottom of this file): walks country.id at load
-- time and log.warns + adds at runtime any keys missing from the static
-- list. This keeps spawn calls working even if a future DCS update
-- introduces a country we haven't catalogued — and surfaces the gap so
-- the static list can be updated to keep editor autocomplete in sync.
--
-- Loading order: sms.lua -> log.lua -> utils.lua -> countries.lua.
--
-- See docs/superpowers/specs/2026-05-01-sms-countries.md.

assert(type(sms) == "table",     "framework/sms.lua must be loaded first")
assert(type(sms.log) == "table", "framework/log.lua must be loaded first")

local log = sms.log.module("sms.countries")

---@class sms.countries
---@field RUSSIA                  "RUSSIA"
---@field UKRAINE                 "UKRAINE"
---@field USA                     "USA"
---@field TURKEY                  "TURKEY"
---@field UK                      "UK"
---@field FRANCE                  "FRANCE"
---@field GERMANY                 "GERMANY"
---@field USAF_AGGRESSORS         "USAF_AGGRESSORS"
---@field CANADA                  "CANADA"
---@field SPAIN                   "SPAIN"
---@field THE_NETHERLANDS         "THE_NETHERLANDS"
---@field BELGIUM                 "BELGIUM"
---@field NORWAY                  "NORWAY"
---@field DENMARK                 "DENMARK"
---@field ISRAEL                  "ISRAEL"
---@field GEORGIA                 "GEORGIA"
---@field INSURGENTS              "INSURGENTS"
---@field ABKHAZIA                "ABKHAZIA"
---@field SOUTH_OSETIA            "SOUTH_OSETIA"
---@field ITALY                   "ITALY"
---@field AUSTRALIA               "AUSTRALIA"
---@field SWITZERLAND             "SWITZERLAND"
---@field AUSTRIA                 "AUSTRIA"
---@field BELARUS                 "BELARUS"
---@field BULGARIA                "BULGARIA"
---@field CHEZH_REPUBLIC          "CHEZH_REPUBLIC"
---@field CHINA                   "CHINA"
---@field CROATIA                 "CROATIA"
---@field EGYPT                   "EGYPT"
---@field FINLAND                 "FINLAND"
---@field GREECE                  "GREECE"
---@field HUNGARY                 "HUNGARY"
---@field INDIA                   "INDIA"
---@field IRAN                    "IRAN"
---@field IRAQ                    "IRAQ"
---@field JAPAN                   "JAPAN"
---@field KAZAKHSTAN              "KAZAKHSTAN"
---@field NORTH_KOREA             "NORTH_KOREA"
---@field PAKISTAN                "PAKISTAN"
---@field POLAND                  "POLAND"
---@field ROMANIA                 "ROMANIA"
---@field SAUDI_ARABIA            "SAUDI_ARABIA"
---@field SERBIA                  "SERBIA"
---@field SLOVAKIA                "SLOVAKIA"
---@field SOUTH_KOREA             "SOUTH_KOREA"
---@field SWEDEN                  "SWEDEN"
---@field SYRIA                   "SYRIA"
---@field YEMEN                   "YEMEN"
---@field VIETNAM                 "VIETNAM"
---@field VENEZUELA               "VENEZUELA"
---@field TUNISIA                 "TUNISIA"
---@field THAILAND                "THAILAND"
---@field SUDAN                   "SUDAN"
---@field PHILIPPINES             "PHILIPPINES"
---@field MOROCCO                 "MOROCCO"
---@field MEXICO                  "MEXICO"
---@field MALAYSIA                "MALAYSIA"
---@field LIBYA                   "LIBYA"
---@field JORDAN                  "JORDAN"
---@field INDONESIA               "INDONESIA"
---@field HONDURAS                "HONDURAS"
---@field ETHIOPIA                "ETHIOPIA"
---@field CHILE                   "CHILE"
---@field BRAZIL                  "BRAZIL"
---@field BAHRAIN                 "BAHRAIN"
---@field THIRDREICH              "THIRDREICH"
---@field YUGOSLAVIA              "YUGOSLAVIA"
---@field USSR                    "USSR"
---@field ITALIAN_SOCIAL_REPUBLIC "ITALIAN_SOCIAL_REPUBLIC"
---@field ALGERIA                 "ALGERIA"
---@field KUWAIT                  "KUWAIT"
---@field QATAR                   "QATAR"
---@field OMAN                    "OMAN"
---@field UAE                     "UAE"
---@field SOUTH_AFRICA            "SOUTH_AFRICA"
---@field CUBA                    "CUBA"
---@field PORTUGAL                "PORTUGAL"
---@field GDR                     "GDR"
---@field LEBANON                 "LEBANON"
---@field CJTF_BLUE               "CJTF_BLUE"
---@field CJTF_RED                "CJTF_RED"
---@field UN_PEACEKEEPERS         "UN_PEACEKEEPERS"
---@field ARGENTINA               "ARGENTINA"
---@field CYPRUS                  "CYPRUS"
---@field SLOVENIA                "SLOVENIA"
---@field BOLIVIA                 "BOLIVIA"
---@field GHANA                   "GHANA"
---@field NIGERIA                 "NIGERIA"
---@field PERU                    "PERU"
---@field ECUADOR                 "ECUADOR"
---@field ESTONIA                 "ESTONIA"
---@field LATVIA                  "LATVIA"
---@field LITHUANIA               "LITHUANIA"
---@field URUGUAY                 "URUGUAY"
sms.countries = sms.countries or {}

---@alias sms.Country
---| "RUSSIA"
---| "UKRAINE"
---| "USA"
---| "TURKEY"
---| "UK"
---| "FRANCE"
---| "GERMANY"
---| "USAF_AGGRESSORS"
---| "CANADA"
---| "SPAIN"
---| "THE_NETHERLANDS"
---| "BELGIUM"
---| "NORWAY"
---| "DENMARK"
---| "ISRAEL"
---| "GEORGIA"
---| "INSURGENTS"
---| "ABKHAZIA"
---| "SOUTH_OSETIA"
---| "ITALY"
---| "AUSTRALIA"
---| "SWITZERLAND"
---| "AUSTRIA"
---| "BELARUS"
---| "BULGARIA"
---| "CHEZH_REPUBLIC"
---| "CHINA"
---| "CROATIA"
---| "EGYPT"
---| "FINLAND"
---| "GREECE"
---| "HUNGARY"
---| "INDIA"
---| "IRAN"
---| "IRAQ"
---| "JAPAN"
---| "KAZAKHSTAN"
---| "NORTH_KOREA"
---| "PAKISTAN"
---| "POLAND"
---| "ROMANIA"
---| "SAUDI_ARABIA"
---| "SERBIA"
---| "SLOVAKIA"
---| "SOUTH_KOREA"
---| "SWEDEN"
---| "SYRIA"
---| "YEMEN"
---| "VIETNAM"
---| "VENEZUELA"
---| "TUNISIA"
---| "THAILAND"
---| "SUDAN"
---| "PHILIPPINES"
---| "MOROCCO"
---| "MEXICO"
---| "MALAYSIA"
---| "LIBYA"
---| "JORDAN"
---| "INDONESIA"
---| "HONDURAS"
---| "ETHIOPIA"
---| "CHILE"
---| "BRAZIL"
---| "BAHRAIN"
---| "THIRDREICH"
---| "YUGOSLAVIA"
---| "USSR"
---| "ITALIAN_SOCIAL_REPUBLIC"
---| "ALGERIA"
---| "KUWAIT"
---| "QATAR"
---| "OMAN"
---| "UAE"
---| "SOUTH_AFRICA"
---| "CUBA"
---| "PORTUGAL"
---| "GDR"
---| "LEBANON"
---| "CJTF_BLUE"
---| "CJTF_RED"
---| "UN_PEACEKEEPERS"
---| "ARGENTINA"
---| "CYPRUS"
---| "SLOVENIA"
---| "BOLIVIA"
---| "GHANA"
---| "NIGERIA"
---| "PERU"
---| "ECUADOR"
---| "ESTONIA"
---| "LATVIA"
---| "LITHUANIA"
---| "URUGUAY"

-- Static enum: every key's value is the key itself, so
-- sms.countries.X == "X" holds for every entry.
sms.countries.RUSSIA                  = "RUSSIA"
sms.countries.UKRAINE                 = "UKRAINE"
sms.countries.USA                     = "USA"
sms.countries.TURKEY                  = "TURKEY"
sms.countries.UK                      = "UK"
sms.countries.FRANCE                  = "FRANCE"
sms.countries.GERMANY                 = "GERMANY"
sms.countries.USAF_AGGRESSORS         = "USAF_AGGRESSORS"
sms.countries.CANADA                  = "CANADA"
sms.countries.SPAIN                   = "SPAIN"
sms.countries.THE_NETHERLANDS         = "THE_NETHERLANDS"
sms.countries.BELGIUM                 = "BELGIUM"
sms.countries.NORWAY                  = "NORWAY"
sms.countries.DENMARK                 = "DENMARK"
sms.countries.ISRAEL                  = "ISRAEL"
sms.countries.GEORGIA                 = "GEORGIA"
sms.countries.INSURGENTS              = "INSURGENTS"
sms.countries.ABKHAZIA                = "ABKHAZIA"
sms.countries.SOUTH_OSETIA            = "SOUTH_OSETIA"
sms.countries.ITALY                   = "ITALY"
sms.countries.AUSTRALIA               = "AUSTRALIA"
sms.countries.SWITZERLAND             = "SWITZERLAND"
sms.countries.AUSTRIA                 = "AUSTRIA"
sms.countries.BELARUS                 = "BELARUS"
sms.countries.BULGARIA                = "BULGARIA"
sms.countries.CHEZH_REPUBLIC          = "CHEZH_REPUBLIC"
sms.countries.CHINA                   = "CHINA"
sms.countries.CROATIA                 = "CROATIA"
sms.countries.EGYPT                   = "EGYPT"
sms.countries.FINLAND                 = "FINLAND"
sms.countries.GREECE                  = "GREECE"
sms.countries.HUNGARY                 = "HUNGARY"
sms.countries.INDIA                   = "INDIA"
sms.countries.IRAN                    = "IRAN"
sms.countries.IRAQ                    = "IRAQ"
sms.countries.JAPAN                   = "JAPAN"
sms.countries.KAZAKHSTAN              = "KAZAKHSTAN"
sms.countries.NORTH_KOREA             = "NORTH_KOREA"
sms.countries.PAKISTAN                = "PAKISTAN"
sms.countries.POLAND                  = "POLAND"
sms.countries.ROMANIA                 = "ROMANIA"
sms.countries.SAUDI_ARABIA            = "SAUDI_ARABIA"
sms.countries.SERBIA                  = "SERBIA"
sms.countries.SLOVAKIA                = "SLOVAKIA"
sms.countries.SOUTH_KOREA             = "SOUTH_KOREA"
sms.countries.SWEDEN                  = "SWEDEN"
sms.countries.SYRIA                   = "SYRIA"
sms.countries.YEMEN                   = "YEMEN"
sms.countries.VIETNAM                 = "VIETNAM"
sms.countries.VENEZUELA               = "VENEZUELA"
sms.countries.TUNISIA                 = "TUNISIA"
sms.countries.THAILAND                = "THAILAND"
sms.countries.SUDAN                   = "SUDAN"
sms.countries.PHILIPPINES             = "PHILIPPINES"
sms.countries.MOROCCO                 = "MOROCCO"
sms.countries.MEXICO                  = "MEXICO"
sms.countries.MALAYSIA                = "MALAYSIA"
sms.countries.LIBYA                   = "LIBYA"
sms.countries.JORDAN                  = "JORDAN"
sms.countries.INDONESIA               = "INDONESIA"
sms.countries.HONDURAS                = "HONDURAS"
sms.countries.ETHIOPIA                = "ETHIOPIA"
sms.countries.CHILE                   = "CHILE"
sms.countries.BRAZIL                  = "BRAZIL"
sms.countries.BAHRAIN                 = "BAHRAIN"
sms.countries.THIRDREICH              = "THIRDREICH"
sms.countries.YUGOSLAVIA              = "YUGOSLAVIA"
sms.countries.USSR                    = "USSR"
sms.countries.ITALIAN_SOCIAL_REPUBLIC = "ITALIAN_SOCIAL_REPUBLIC"
sms.countries.ALGERIA                 = "ALGERIA"
sms.countries.KUWAIT                  = "KUWAIT"
sms.countries.QATAR                   = "QATAR"
sms.countries.OMAN                    = "OMAN"
sms.countries.UAE                     = "UAE"
sms.countries.SOUTH_AFRICA            = "SOUTH_AFRICA"
sms.countries.CUBA                    = "CUBA"
sms.countries.PORTUGAL                = "PORTUGAL"
sms.countries.GDR                     = "GDR"
sms.countries.LEBANON                 = "LEBANON"
sms.countries.CJTF_BLUE               = "CJTF_BLUE"
sms.countries.CJTF_RED                = "CJTF_RED"
sms.countries.UN_PEACEKEEPERS         = "UN_PEACEKEEPERS"
sms.countries.ARGENTINA               = "ARGENTINA"
sms.countries.CYPRUS                  = "CYPRUS"
sms.countries.SLOVENIA                = "SLOVENIA"
sms.countries.BOLIVIA                 = "BOLIVIA"
sms.countries.GHANA                   = "GHANA"
sms.countries.NIGERIA                 = "NIGERIA"
sms.countries.PERU                    = "PERU"
sms.countries.ECUADOR                 = "ECUADOR"
sms.countries.ESTONIA                 = "ESTONIA"
sms.countries.LATVIA                  = "LATVIA"
sms.countries.LITHUANIA               = "LITHUANIA"
sms.countries.URUGUAY                 = "URUGUAY"

-- Runtime drift check. country is the DCS global; country.id is a
-- {KEY = int} hash of every country DCS knows about. If a key is in
-- country.id but not in the static list above, add it at runtime so
-- spawn calls keep working, and log a one-shot warn so the gap is
-- visible. Guarded so this file is loadable outside DCS (e.g. host-side
-- tests that don't have the country global).
if type(country) == "table" and type(country.id) == "table" then
  for key in pairs(country.id) do
    if type(key) == "string" and sms.countries[key] == nil then
      sms.countries[key] = key
      log.warn("country.id key '" .. key .. "' not in static list — added at runtime; update framework/countries.lua to keep autocomplete in sync")
    end
  end
end
