-- AUTO-GENERATED by `dcs-sms gen-units`. Do not edit by hand.
-- Source: dcs-lua-datamine @   (regenerated 2026-04-30T15:49:07Z)
-- See docs/api/statics.md for usage.

assert(type(sms) == "table", "framework/sms.lua must be loaded first")
local log = sms.log.module("sms.statics")

---@alias sms.StaticSpawnType
---| ".Ammunition depot"
---| ".Command Center"
---| "345 Excavator"
---| "463_Pallet"
---| "AM32a-60_01"
---| "AM32a-60_02"
---| "APFC fuel"
---| "AS32-31A"
---| "AS32-32A"
---| "AS32-36A"
---| "AS32-p25"
---| "Airshow_Cone"
---| "Airshow_Crowd"
---| "B600"
---| "Barracks 2"
---| "Barrier A"
---| "Barrier B"
---| "Barrier C"
---| "Barrier D"
---| "Beer Bomb"
---| "Belgian gate"
---| "Black_Tyre"
---| "Black_Tyre_RF"
---| "Black_Tyre_WF"
---| "Boiler-house A"
---| "BoomBarrier_closed"
---| "BoomBarrier_open"
---| "Bridge"
---| "Building"
---| "Building01_PBR"
---| "Building02_PBR"
---| "Building03_PBR"
---| "Building04_PBR"
---| "Building05_PBR"
---| "Building06_PBR"
---| "Building07_PBR"
---| "Building08_PBR"
---| "Bunker"
---| "CV_59_H60"
---| "CV_59_Large_Forklift"
---| "CV_59_MD3"
---| "CV_59_NS60"
---| "Cafe"
---| "Camouflage01"
---| "Camouflage02"
---| "Camouflage03"
---| "Camouflage04"
---| "Camouflage05"
---| "Camouflage06"
---| "Camouflage07"
---| "Cargo01"
---| "Cargo02"
---| "Cargo03"
---| "Cargo04"
---| "Cargo05"
---| "Cargo06"
---| "Carrier Airboss"
---| "Carrier LSO Personell"
---| "Carrier LSO Personell 1"
---| "Carrier LSO Personell 2"
---| "Carrier LSO Personell 3"
---| "Carrier LSO Personell 4"
---| "Carrier LSO Personell 5"
---| "Carrier Seaman"
---| "Chemical tank A"
---| "Comms tower M"
---| "Concertina wire"
---| "Cone01"
---| "Cone02"
---| "Container brown"
---| "Container red 1"
---| "Container red 2"
---| "Container red 3"
---| "Container white"
---| "Container_10ft"
---| "Container_generator"
---| "Container_office"
---| "Container_watchtower"
---| "Container_watchtower_lights"
---| "Cow"
---| "Czech hedgehogs 1"
---| "Czech hedgehogs 2"
---| "Dragonteeth 1"
---| "Dragonteeth 2"
---| "Dragonteeth 3"
---| "Dragonteeth 4"
---| "Dragonteeth 5"
---| "Drop Zone Marker A"
---| "Drop Zone Marker B"
---| "Drop Zone Marker C"
---| "Drop Zone Marker D"
---| "Drop Zone Marker E"
---| "Electric power box"
---| "ElevatedPlatform_down"
---| "ElevatedPlatform_up"
---| "FARP"
---| "FARP Ammo Dump Coating"
---| "FARP CP Blindage"
---| "FARP Fuel Depot"
---| "FARP Tent"
---| "FARP_SINGLE_01"
---| "Farm A"
---| "Farm B"
---| "FarpHide_Dmed"
---| "FarpHide_Dsmall"
---| "FarpHide_Med"
---| "FarpHide_small"
---| "Fire Control Bunker"
---| "FireExtinguisher01"
---| "FireExtinguisher02"
---| "FireExtinguisher03"
---| "FlagPole"
---| "Freya_Shelter_Brick"
---| "Freya_Shelter_Concrete"
---| "Fuel tank"
---| "Garage A"
---| "Garage B"
---| "Garage small A"
---| "Garage small B"
---| "Gas platform"
---| "GeneratorF"
---| "GrassAirfield"
---| "HESCO_generator"
---| "HESCO_post_1"
---| "HESCO_wallperimeter_1"
---| "HESCO_wallperimeter_2"
---| "HESCO_wallperimeter_3"
---| "HESCO_wallperimeter_4"
---| "HESCO_wallperimeter_5"
---| "HESCO_watchtower_1"
---| "HESCO_watchtower_2"
---| "HESCO_watchtower_3"
---| "Hangar A"
---| "Hangar B"
---| "Haystack 1"
---| "Haystack 2"
---| "Haystack 3"
---| "Haystack 4"
---| "Hemmkurvenhindernis"
---| "Invisible FARP"
---| "Jerrycan"
---| "LHD_LHA"
---| "Ladder"
---| "Landmine"
---| "Log posts 1"
---| "Log posts 2"
---| "Log posts 3"
---| "Log ramps 1"
---| "Log ramps 2"
---| "Log ramps 3"
---| "M32-10C_01"
---| "M32-10C_02"
---| "M32-10C_03"
---| "M32-10C_04"
---| "M92_10Ft_Container"
---| "M92_Ammo_Pallet"
---| "M92_Concrete_Barrier_Cargo"
---| "M92_MRE_Pallet"
---| "MJ-1_01"
---| "MJ-1_02"
---| "Military staff"
---| "NF-2_LightOff01"
---| "NF-2_LightOff02"
---| "NF-2_LightOn"
---| "Nodding_Donkey_Pump"
---| "Oil Barrel"
---| "Oil derrick"
---| "Oil platform"
---| "Oil rig"
---| "Orca"
---| "P20_01"
---| "Pile of Woods"
---| "Pump station"
---| "Railway crossing A"
---| "Railway crossing B"
---| "Railway station"
---| "Red_Flag"
---| "Repair workshop"
---| "Restaurant 1"
---| "Revetment_x4"
---| "Revetment_x8"
---| "SA Ski Ramp"
---| "SINGLE_HELIPAD"
---| "SK_C_28_naval_gun"
---| "Sandbag_01"
---| "Sandbag_02"
---| "Sandbag_03"
---| "Sandbag_04"
---| "Sandbag_05"
---| "Sandbag_06"
---| "Sandbag_07"
---| "Sandbag_08"
---| "Sandbag_09"
---| "Sandbag_10"
---| "Sandbag_11"
---| "Sandbag_12"
---| "Sandbag_13"
---| "Sandbag_15"
---| "Sandbag_16"
---| "Sandbag_17"
---| "Sandbox"
---| "Shelter"
---| "Shelter B"
---| "Shelter01"
---| "Shelter02"
---| "Shop"
---| "Siegfried Line"
---| "Ski Ramp"
---| "Small house 1A"
---| "Small house 1A area"
---| "Small house 1B"
---| "Small house 1B area"
---| "Small house 1C area"
---| "Small house 2C"
---| "Small werehouse 1"
---| "Small werehouse 2"
---| "Small werehouse 3"
---| "Small werehouse 4"
---| "Small_LightHouse"
---| "Stanley_LightHouse"
---| "Subsidiary structure 1"
---| "Subsidiary structure 2"
---| "Subsidiary structure 3"
---| "Subsidiary structure A"
---| "Subsidiary structure B"
---| "Subsidiary structure C"
---| "Subsidiary structure D"
---| "Subsidiary structure E"
---| "Subsidiary structure F"
---| "Subsidiary structure G"
---| "Supermarket A"
---| "TACAN_beacon"
---| "TV tower"
---| "Tank"
---| "Tank 2"
---| "Tank 3"
---| "Tech combine"
---| "Tech hangar A"
---| "Tent01"
---| "Tent02"
---| "Tent03"
---| "Tent04"
---| "Tent05"
---| "Tetrahydra"
---| "Toolbox01"
---| "Toolbox02"
---| "Tower Crane"
---| "Train"
---| "Transport"
---| "TugHarlan"
---| "Twall_x1"
---| "Twall_x6"
---| "Twall_x6_3mts"
---| "WC"
---| "Warehouse"
---| "Water tower A"
---| "White_Flag"
---| "White_Tyre"
---| "WindTurbine"
---| "WindTurbine_11"
---| "Windsock"
---| "Workshop A"
---| "af_hq"
---| "ammo_cargo"
---| "barrels_cargo"
---| "big_smoke"
---| "billboard_motorized"
---| "cds_barrels"
---| "cds_crate"
---| "container_20ft"
---| "container_40ft"
---| "container_cargo"
---| "f_bar_cargo"
---| "fire_control"
---| "fueltank_cargo"
---| "gbu_43b_airdrop"
---| "house1arm"
---| "house2arm"
---| "houseA_arm"
---| "ip_tower"
---| "iso_container"
---| "iso_container_small"
---| "l118"
---| "m117_cargo"
---| "m1_vla"
---| "offshore WindTurbine"
---| "offshore WindTurbine2"
---| "oiltank_cargo"
---| "outpost"
---| "outpost_road"
---| "outpost_road_l"
---| "outpost_road_r"
---| "pipes_big_cargo"
---| "pipes_small_cargo"
---| "r11_volvo"
---| "tetrapod_cargo"
---| "trunks_long_cargo"
---| "trunks_small_cargo"
---| "uh1h_cargo"
---| "us carrier shooter"
---| "us carrier tech"
---| "warning_board_a"
---| "warning_board_b"
---| "wp_marker"

---@class sms.statics
sms.statics = sms.statics or {}

sms.statics.airfields = {
  GrassAirfield = "GrassAirfield",
}

sms.statics.airships = {
  m1_vla = "m1_vla",                                         -- WWII Assets
}

sms.statics.animals = {
  Cow = "Cow",                                               -- Animals
}

sms.statics.cargos = {
  M92_10Ft_Container = "M92_10Ft_Container",                 -- C-130 Assets
  M92_Ammo_Pallet = "M92_Ammo_Pallet",                       -- C-130 Assets
  M92_Concrete_Barrier_Cargo = "M92_Concrete_Barrier_Cargo", -- C-130 Assets
  M92_MRE_Pallet = "M92_MRE_Pallet",                         -- C-130 Assets
  _463_Pallet = "463_Pallet",                                -- C-130 Assets
  ammo_cargo = "ammo_cargo",
  barrels_cargo = "barrels_cargo",
  cds_barrels = "cds_barrels",                               -- C-130 Assets
  cds_crate = "cds_crate",                                   -- C-130 Assets
  container_cargo = "container_cargo",
  f_bar_cargo = "f_bar_cargo",
  fueltank_cargo = "fueltank_cargo",
  gbu_43b_airdrop = "gbu_43b_airdrop",
  iso_container = "iso_container",
  iso_container_small = "iso_container_small",
  l118 = "l118",                                             -- South Atlantic Assets
  m117_cargo = "m117_cargo",
  oiltank_cargo = "oiltank_cargo",
  pipes_big_cargo = "pipes_big_cargo",
  pipes_small_cargo = "pipes_small_cargo",
  tetrapod_cargo = "tetrapod_cargo",
  trunks_long_cargo = "trunks_long_cargo",
  trunks_small_cargo = "trunks_small_cargo",
  uh1h_cargo = "uh1h_cargo",
}

sms.statics.effects = {
  big_smoke = "big_smoke",
  wp_marker = "wp_marker",
}

sms.statics.equipment = {
  AS32_31A = "AS32-31A",                                     -- Supercarrier
  AS32_32A = "AS32-32A",                                     -- Supercarrier
  AS32_36A = "AS32-36A",                                     -- Supercarrier
  AS32_p25 = "AS32-p25",                                     -- Supercarrier
  CV_59_H60 = "CV_59_H60",
  CV_59_Large_Forklift = "CV_59_Large_Forklift",
  CV_59_MD3 = "CV_59_MD3",
  CV_59_NS60 = "CV_59_NS60",
  SA_Ski_Ramp = "SA Ski Ramp",                               -- South Atlantic Assets
  Ski_Ramp = "Ski Ramp",                                     -- South Atlantic Assets
}

sms.statics.fortifications = {
  AM32a_60_01 = "AM32a-60_01",                               -- Massun92 Assets
  AM32a_60_02 = "AM32a-60_02",                               -- Massun92 Assets
  APFC_fuel = "APFC fuel",                                   -- Massun92 Assets
  Airshow_Cone = "Airshow_Cone",
  Airshow_Crowd = "Airshow_Crowd",
  B600 = "B600",                                             -- Massun92 Assets
  Barracks_2 = "Barracks 2",
  Barrier_A = "Barrier A",                                   -- Massun92 Assets
  Barrier_B = "Barrier B",                                   -- Massun92 Assets
  Barrier_C = "Barrier C",                                   -- Massun92 Assets
  Barrier_D = "Barrier D",                                   -- Massun92 Assets
  Beer_Bomb = "Beer Bomb",                                   -- WWII Assets
  Belgian_gate = "Belgian gate",                             -- WWII Assets
  Black_Tyre = "Black_Tyre",
  Black_Tyre_RF = "Black_Tyre_RF",
  Black_Tyre_WF = "Black_Tyre_WF",
  Boiler_house_A = "Boiler-house A",
  BoomBarrier_closed = "BoomBarrier_closed",                 -- Massun92 Assets
  BoomBarrier_open = "BoomBarrier_open",                     -- Massun92 Assets
  Building01_PBR = "Building01_PBR",                         -- Massun92 Assets
  Building02_PBR = "Building02_PBR",                         -- Massun92 Assets
  Building03_PBR = "Building03_PBR",                         -- Massun92 Assets
  Building04_PBR = "Building04_PBR",                         -- Massun92 Assets
  Building05_PBR = "Building05_PBR",                         -- Massun92 Assets
  Building06_PBR = "Building06_PBR",                         -- Massun92 Assets
  Building07_PBR = "Building07_PBR",                         -- Massun92 Assets
  Building08_PBR = "Building08_PBR",                         -- Massun92 Assets
  Bunker = "Bunker",
  Cafe = "Cafe",
  Camouflage01 = "Camouflage01",                             -- Massun92 Assets
  Camouflage02 = "Camouflage02",                             -- Massun92 Assets
  Camouflage03 = "Camouflage03",                             -- Massun92 Assets
  Camouflage04 = "Camouflage04",                             -- Massun92 Assets
  Camouflage05 = "Camouflage05",                             -- Massun92 Assets
  Camouflage06 = "Camouflage06",                             -- Massun92 Assets
  Camouflage07 = "Camouflage07",                             -- Massun92 Assets
  Cargo01 = "Cargo01",                                       -- Massun92 Assets
  Cargo02 = "Cargo02",                                       -- Massun92 Assets
  Cargo03 = "Cargo03",                                       -- Massun92 Assets
  Cargo04 = "Cargo04",                                       -- Massun92 Assets
  Cargo05 = "Cargo05",                                       -- Massun92 Assets
  Cargo06 = "Cargo06",                                       -- Massun92 Assets
  Chemical_tank_A = "Chemical tank A",
  Comms_tower_M = "Comms tower M",
  Concertina_wire = "Concertina wire",                       -- WWII Assets
  Cone01 = "Cone01",                                         -- Massun92 Assets
  Cone02 = "Cone02",                                         -- Massun92 Assets
  Container_10ft = "Container_10ft",                         -- Massun92 Assets
  Container_brown = "Container brown",
  Container_generator = "Container_generator",               -- Massun92 Assets
  Container_office = "Container_office",                     -- Massun92 Assets
  Container_red_1 = "Container red 1",
  Container_red_2 = "Container red 2",
  Container_red_3 = "Container red 3",
  Container_watchtower = "Container_watchtower",             -- Massun92 Assets
  Container_watchtower_lights = "Container_watchtower_lights", -- Massun92 Assets
  Container_white = "Container white",
  Czech_hedgehogs_1 = "Czech hedgehogs 1",                   -- WWII Assets
  Czech_hedgehogs_2 = "Czech hedgehogs 2",                   -- WWII Assets
  Dragonteeth_1 = "Dragonteeth 1",                           -- WWII Assets
  Dragonteeth_2 = "Dragonteeth 2",                           -- WWII Assets
  Dragonteeth_3 = "Dragonteeth 3",                           -- WWII Assets
  Dragonteeth_4 = "Dragonteeth 4",                           -- WWII Assets
  Dragonteeth_5 = "Dragonteeth 5",                           -- WWII Assets
  Drop_Zone_Marker_A = "Drop Zone Marker A",                 -- C-130 Assets
  Drop_Zone_Marker_B = "Drop Zone Marker B",                 -- C-130 Assets
  Drop_Zone_Marker_C = "Drop Zone Marker C",                 -- C-130 Assets
  Drop_Zone_Marker_D = "Drop Zone Marker D",                 -- C-130 Assets
  Drop_Zone_Marker_E = "Drop Zone Marker E",                 -- C-130 Assets
  Electric_power_box = "Electric power box",
  ElevatedPlatform_down = "ElevatedPlatform_down",           -- Massun92 Assets
  ElevatedPlatform_up = "ElevatedPlatform_up",               -- Massun92 Assets
  FARP_Ammo_Dump_Coating = "FARP Ammo Dump Coating",
  FARP_CP_Blindage = "FARP CP Blindage",
  FARP_Fuel_Depot = "FARP Fuel Depot",
  FARP_Tent = "FARP Tent",
  Farm_A = "Farm A",
  Farm_B = "Farm B",
  FarpHide_Dmed = "FarpHide_Dmed",                           -- South Atlantic Assets
  FarpHide_Dsmall = "FarpHide_Dsmall",                       -- South Atlantic Assets
  FarpHide_Med = "FarpHide_Med",                             -- South Atlantic Assets
  FarpHide_small = "FarpHide_small",                         -- South Atlantic Assets
  FireExtinguisher01 = "FireExtinguisher01",                 -- Massun92 Assets
  FireExtinguisher02 = "FireExtinguisher02",                 -- Massun92 Assets
  FireExtinguisher03 = "FireExtinguisher03",                 -- Massun92 Assets
  Fire_Control_Bunker = "Fire Control Bunker",               -- WWII Assets
  FlagPole = "FlagPole",                                     -- Tech Weapon Pack
  Freya_Shelter_Brick = "Freya_Shelter_Brick",               -- WWII Assets
  Freya_Shelter_Concrete = "Freya_Shelter_Concrete",         -- WWII Assets
  Fuel_tank = "Fuel tank",
  Garage_A = "Garage A",
  Garage_B = "Garage B",
  Garage_small_A = "Garage small A",
  Garage_small_B = "Garage small B",
  GeneratorF = "GeneratorF",
  HESCO_generator = "HESCO_generator",                       -- Massun92 Assets
  HESCO_post_1 = "HESCO_post_1",                             -- Massun92 Assets
  HESCO_wallperimeter_1 = "HESCO_wallperimeter_1",           -- Massun92 Assets
  HESCO_wallperimeter_2 = "HESCO_wallperimeter_2",           -- Massun92 Assets
  HESCO_wallperimeter_3 = "HESCO_wallperimeter_3",           -- Massun92 Assets
  HESCO_wallperimeter_4 = "HESCO_wallperimeter_4",           -- Massun92 Assets
  HESCO_wallperimeter_5 = "HESCO_wallperimeter_5",           -- Massun92 Assets
  HESCO_watchtower_1 = "HESCO_watchtower_1",                 -- Massun92 Assets
  HESCO_watchtower_2 = "HESCO_watchtower_2",                 -- Massun92 Assets
  HESCO_watchtower_3 = "HESCO_watchtower_3",                 -- Massun92 Assets
  Hangar_A = "Hangar A",
  Hangar_B = "Hangar B",
  Haystack_1 = "Haystack 1",                                 -- WWII Assets
  Haystack_2 = "Haystack 2",                                 -- WWII Assets
  Haystack_3 = "Haystack 3",                                 -- WWII Assets
  Haystack_4 = "Haystack 4",                                 -- WWII Assets
  Hemmkurvenhindernis = "Hemmkurvenhindernis",               -- WWII Assets
  Jerrycan = "Jerrycan",                                     -- Massun92 Assets
  LHD_LHA = "LHD_LHA",                                       -- Massun92 Assets
  Ladder = "Ladder",                                         -- Massun92 Assets
  Landmine = "Landmine",
  Log_posts_1 = "Log posts 1",                               -- WWII Assets
  Log_posts_2 = "Log posts 2",                               -- WWII Assets
  Log_posts_3 = "Log posts 3",                               -- WWII Assets
  Log_ramps_1 = "Log ramps 1",                               -- WWII Assets
  Log_ramps_2 = "Log ramps 2",                               -- WWII Assets
  Log_ramps_3 = "Log ramps 3",                               -- WWII Assets
  M32_10C_01 = "M32-10C_01",                                 -- Massun92 Assets
  M32_10C_02 = "M32-10C_02",                                 -- Massun92 Assets
  M32_10C_03 = "M32-10C_03",                                 -- Massun92 Assets
  M32_10C_04 = "M32-10C_04",                                 -- Massun92 Assets
  MJ_1_01 = "MJ-1_01",                                       -- Massun92 Assets
  MJ_1_02 = "MJ-1_02",                                       -- Massun92 Assets
  Military_staff = "Military staff",
  NF_2_LightOff01 = "NF-2_LightOff01",                       -- Massun92 Assets
  NF_2_LightOff02 = "NF-2_LightOff02",                       -- Massun92 Assets
  NF_2_LightOn = "NF-2_LightOn",                             -- Massun92 Assets
  Nodding_Donkey_Pump = "Nodding_Donkey_Pump",               -- South Atlantic Assets
  Oil_Barrel = "Oil Barrel",                                 -- Massun92 Assets
  Oil_derrick = "Oil derrick",
  Oil_platform = "Oil platform",
  Orca = "Orca",                                             -- South Atlantic Assets
  P20_01 = "P20_01",                                         -- Massun92 Assets
  Pile_of_Woods = "Pile of Woods",                           -- Massun92 Assets
  Pump_station = "Pump station",
  Railway_crossing_A = "Railway crossing A",
  Railway_crossing_B = "Railway crossing B",
  Railway_station = "Railway station",
  Red_Flag = "Red_Flag",
  Repair_workshop = "Repair workshop",
  Restaurant_1 = "Restaurant 1",
  Revetment_x4 = "Revetment_x4",                             -- Massun92 Assets
  Revetment_x8 = "Revetment_x8",                             -- Massun92 Assets
  SK_C_28_naval_gun = "SK_C_28_naval_gun",                   -- WWII Assets
  Sandbag_01 = "Sandbag_01",                                 -- Massun92 Assets
  Sandbag_02 = "Sandbag_02",                                 -- Massun92 Assets
  Sandbag_03 = "Sandbag_03",                                 -- Massun92 Assets
  Sandbag_04 = "Sandbag_04",                                 -- Massun92 Assets
  Sandbag_05 = "Sandbag_05",                                 -- Massun92 Assets
  Sandbag_06 = "Sandbag_06",                                 -- Massun92 Assets
  Sandbag_07 = "Sandbag_07",                                 -- Massun92 Assets
  Sandbag_08 = "Sandbag_08",                                 -- Massun92 Assets
  Sandbag_09 = "Sandbag_09",                                 -- Massun92 Assets
  Sandbag_10 = "Sandbag_10",                                 -- Massun92 Assets
  Sandbag_11 = "Sandbag_11",                                 -- Massun92 Assets
  Sandbag_12 = "Sandbag_12",                                 -- Massun92 Assets
  Sandbag_13 = "Sandbag_13",                                 -- Massun92 Assets
  Sandbag_15 = "Sandbag_15",                                 -- Massun92 Assets
  Sandbag_16 = "Sandbag_16",                                 -- Massun92 Assets
  Sandbag_17 = "Sandbag_17",                                 -- Massun92 Assets
  Sandbox = "Sandbox",
  Shelter = "Shelter",
  Shelter01 = "Shelter01",                                   -- Massun92 Assets
  Shelter02 = "Shelter02",                                   -- Massun92 Assets
  Shelter_B = "Shelter B",
  Shop = "Shop",
  Siegfried_Line = "Siegfried Line",                         -- WWII Assets
  Small_LightHouse = "Small_LightHouse",                     -- South Atlantic Assets
  Small_house_1A = "Small house 1A",
  Small_house_1A_area = "Small house 1A area",
  Small_house_1B = "Small house 1B",
  Small_house_1B_area = "Small house 1B area",
  Small_house_1C_area = "Small house 1C area",
  Small_house_2C = "Small house 2C",
  Small_werehouse_1 = "Small werehouse 1",
  Small_werehouse_2 = "Small werehouse 2",
  Small_werehouse_3 = "Small werehouse 3",
  Small_werehouse_4 = "Small werehouse 4",
  Stanley_LightHouse = "Stanley_LightHouse",                 -- South Atlantic Assets
  Subsidiary_structure_1 = "Subsidiary structure 1",
  Subsidiary_structure_2 = "Subsidiary structure 2",
  Subsidiary_structure_3 = "Subsidiary structure 3",
  Subsidiary_structure_A = "Subsidiary structure A",
  Subsidiary_structure_B = "Subsidiary structure B",
  Subsidiary_structure_C = "Subsidiary structure C",
  Subsidiary_structure_D = "Subsidiary structure D",
  Subsidiary_structure_E = "Subsidiary structure E",
  Subsidiary_structure_F = "Subsidiary structure F",
  Subsidiary_structure_G = "Subsidiary structure G",
  Supermarket_A = "Supermarket A",
  TACAN_beacon = "TACAN_beacon",
  TV_tower = "TV tower",
  Tech_combine = "Tech combine",
  Tech_hangar_A = "Tech hangar A",
  Tent01 = "Tent01",                                         -- Massun92 Assets
  Tent02 = "Tent02",                                         -- Massun92 Assets
  Tent03 = "Tent03",                                         -- Massun92 Assets
  Tent04 = "Tent04",                                         -- Massun92 Assets
  Tent05 = "Tent05",                                         -- Massun92 Assets
  Tetrahydra = "Tetrahydra",                                 -- WWII Assets
  Toolbox01 = "Toolbox01",                                   -- Massun92 Assets
  Toolbox02 = "Toolbox02",                                   -- Massun92 Assets
  Tower_Crane = "Tower Crane",                               -- South Atlantic Assets
  TugHarlan = "TugHarlan",                                   -- Massun92 Assets
  Twall_x1 = "Twall_x1",                                     -- Massun92 Assets
  Twall_x6 = "Twall_x6",                                     -- Massun92 Assets
  Twall_x6_3mts = "Twall_x6_3mts",                           -- Massun92 Assets
  WC = "WC",
  Water_tower_A = "Water tower A",
  White_Flag = "White_Flag",
  White_Tyre = "White_Tyre",
  WindTurbine = "WindTurbine",                               -- South Atlantic Assets
  WindTurbine_11 = "WindTurbine_11",                         -- South Atlantic Assets
  Windsock = "Windsock",
  Workshop_A = "Workshop A",
  _345_Excavator = "345 Excavator",                          -- South Atlantic Assets
  _Command_Center = ".Command Center",
  af_hq = "af_hq",
  billboard_motorized = "billboard_motorized",               -- South Atlantic Assets
  container_20ft = "container_20ft",                         -- Tech Weapon Pack
  container_40ft = "container_40ft",                         -- Tech Weapon Pack
  fire_control = "fire_control",                             -- WWII Assets
  house1arm = "house1arm",
  house2arm = "house2arm",
  houseA_arm = "houseA_arm",
  ip_tower = "ip_tower",
  offshore_WindTurbine = "offshore WindTurbine",             -- South Atlantic Assets
  offshore_WindTurbine2 = "offshore WindTurbine2",           -- South Atlantic Assets
  outpost = "outpost",
  outpost_road = "outpost_road",
  outpost_road_l = "outpost_road_l",
  outpost_road_r = "outpost_road_r",
  r11_volvo = "r11_volvo",                                   -- Massun92 Assets
  warning_board_a = "warning_board_a",                       -- China Asset Pack
  warning_board_b = "warning_board_b",                       -- China Asset Pack
}

sms.statics.ground_objects = {
  Bridge = "Bridge",
  Building = "Building",
  Train = "Train",
  Transport = "Transport",
}

sms.statics.heliports = {
  FARP = "FARP",
  FARP_SINGLE_01 = "FARP_SINGLE_01",                         -- South Atlantic Assets
  Gas_platform = "Gas platform",                             -- Tech Weapon Pack
  Invisible_FARP = "Invisible FARP",
  Oil_rig = "Oil rig",                                       -- Tech Weapon Pack
  SINGLE_HELIPAD = "SINGLE_HELIPAD",
}

sms.statics.personnel = {
  Carrier_Airboss = "Carrier Airboss",                       -- Supercarrier
  Carrier_LSO_Personell = "Carrier LSO Personell",           -- Supercarrier
  Carrier_LSO_Personell_1 = "Carrier LSO Personell 1",       -- Supercarrier
  Carrier_LSO_Personell_2 = "Carrier LSO Personell 2",       -- Supercarrier
  Carrier_LSO_Personell_3 = "Carrier LSO Personell 3",       -- Supercarrier
  Carrier_LSO_Personell_4 = "Carrier LSO Personell 4",       -- Supercarrier
  Carrier_LSO_Personell_5 = "Carrier LSO Personell 5",       -- Supercarrier
  Carrier_Seaman = "Carrier Seaman",                         -- Supercarrier
  us_carrier_shooter = "us carrier shooter",                 -- Supercarrier
  us_carrier_tech = "us carrier tech",                       -- Supercarrier
}

sms.statics.warehouses = {
  Tank = "Tank",
  Tank_2 = "Tank 2",
  Tank_3 = "Tank 3",
  Warehouse = "Warehouse",
  _Ammunition_depot = ".Ammunition depot",
}

-- ============================================================
-- Origin lookup
-- ============================================================

local _origin = {
  ["345 Excavator"] = "South Atlantic Assets",
  ["463_Pallet"] = "C-130 Assets",
  ["AM32a-60_01"] = "Massun92 Assets",
  ["AM32a-60_02"] = "Massun92 Assets",
  ["APFC fuel"] = "Massun92 Assets",
  ["AS32-31A"] = "Supercarrier",
  ["AS32-32A"] = "Supercarrier",
  ["AS32-36A"] = "Supercarrier",
  ["AS32-p25"] = "Supercarrier",
  ["B600"] = "Massun92 Assets",
  ["Barrier A"] = "Massun92 Assets",
  ["Barrier B"] = "Massun92 Assets",
  ["Barrier C"] = "Massun92 Assets",
  ["Barrier D"] = "Massun92 Assets",
  ["Beer Bomb"] = "WWII Assets",
  ["Belgian gate"] = "WWII Assets",
  ["BoomBarrier_closed"] = "Massun92 Assets",
  ["BoomBarrier_open"] = "Massun92 Assets",
  ["Building01_PBR"] = "Massun92 Assets",
  ["Building02_PBR"] = "Massun92 Assets",
  ["Building03_PBR"] = "Massun92 Assets",
  ["Building04_PBR"] = "Massun92 Assets",
  ["Building05_PBR"] = "Massun92 Assets",
  ["Building06_PBR"] = "Massun92 Assets",
  ["Building07_PBR"] = "Massun92 Assets",
  ["Building08_PBR"] = "Massun92 Assets",
  ["Camouflage01"] = "Massun92 Assets",
  ["Camouflage02"] = "Massun92 Assets",
  ["Camouflage03"] = "Massun92 Assets",
  ["Camouflage04"] = "Massun92 Assets",
  ["Camouflage05"] = "Massun92 Assets",
  ["Camouflage06"] = "Massun92 Assets",
  ["Camouflage07"] = "Massun92 Assets",
  ["Cargo01"] = "Massun92 Assets",
  ["Cargo02"] = "Massun92 Assets",
  ["Cargo03"] = "Massun92 Assets",
  ["Cargo04"] = "Massun92 Assets",
  ["Cargo05"] = "Massun92 Assets",
  ["Cargo06"] = "Massun92 Assets",
  ["Carrier Airboss"] = "Supercarrier",
  ["Carrier LSO Personell"] = "Supercarrier",
  ["Carrier LSO Personell 1"] = "Supercarrier",
  ["Carrier LSO Personell 2"] = "Supercarrier",
  ["Carrier LSO Personell 3"] = "Supercarrier",
  ["Carrier LSO Personell 4"] = "Supercarrier",
  ["Carrier LSO Personell 5"] = "Supercarrier",
  ["Carrier Seaman"] = "Supercarrier",
  ["Concertina wire"] = "WWII Assets",
  ["Cone01"] = "Massun92 Assets",
  ["Cone02"] = "Massun92 Assets",
  ["Container_10ft"] = "Massun92 Assets",
  ["Container_generator"] = "Massun92 Assets",
  ["Container_office"] = "Massun92 Assets",
  ["Container_watchtower"] = "Massun92 Assets",
  ["Container_watchtower_lights"] = "Massun92 Assets",
  ["Cow"] = "Animals",
  ["Czech hedgehogs 1"] = "WWII Assets",
  ["Czech hedgehogs 2"] = "WWII Assets",
  ["Dragonteeth 1"] = "WWII Assets",
  ["Dragonteeth 2"] = "WWII Assets",
  ["Dragonteeth 3"] = "WWII Assets",
  ["Dragonteeth 4"] = "WWII Assets",
  ["Dragonteeth 5"] = "WWII Assets",
  ["Drop Zone Marker A"] = "C-130 Assets",
  ["Drop Zone Marker B"] = "C-130 Assets",
  ["Drop Zone Marker C"] = "C-130 Assets",
  ["Drop Zone Marker D"] = "C-130 Assets",
  ["Drop Zone Marker E"] = "C-130 Assets",
  ["ElevatedPlatform_down"] = "Massun92 Assets",
  ["ElevatedPlatform_up"] = "Massun92 Assets",
  ["FARP_SINGLE_01"] = "South Atlantic Assets",
  ["FarpHide_Dmed"] = "South Atlantic Assets",
  ["FarpHide_Dsmall"] = "South Atlantic Assets",
  ["FarpHide_Med"] = "South Atlantic Assets",
  ["FarpHide_small"] = "South Atlantic Assets",
  ["Fire Control Bunker"] = "WWII Assets",
  ["FireExtinguisher01"] = "Massun92 Assets",
  ["FireExtinguisher02"] = "Massun92 Assets",
  ["FireExtinguisher03"] = "Massun92 Assets",
  ["FlagPole"] = "Tech Weapon Pack",
  ["Freya_Shelter_Brick"] = "WWII Assets",
  ["Freya_Shelter_Concrete"] = "WWII Assets",
  ["Gas platform"] = "Tech Weapon Pack",
  ["HESCO_generator"] = "Massun92 Assets",
  ["HESCO_post_1"] = "Massun92 Assets",
  ["HESCO_wallperimeter_1"] = "Massun92 Assets",
  ["HESCO_wallperimeter_2"] = "Massun92 Assets",
  ["HESCO_wallperimeter_3"] = "Massun92 Assets",
  ["HESCO_wallperimeter_4"] = "Massun92 Assets",
  ["HESCO_wallperimeter_5"] = "Massun92 Assets",
  ["HESCO_watchtower_1"] = "Massun92 Assets",
  ["HESCO_watchtower_2"] = "Massun92 Assets",
  ["HESCO_watchtower_3"] = "Massun92 Assets",
  ["Haystack 1"] = "WWII Assets",
  ["Haystack 2"] = "WWII Assets",
  ["Haystack 3"] = "WWII Assets",
  ["Haystack 4"] = "WWII Assets",
  ["Hemmkurvenhindernis"] = "WWII Assets",
  ["Jerrycan"] = "Massun92 Assets",
  ["LHD_LHA"] = "Massun92 Assets",
  ["Ladder"] = "Massun92 Assets",
  ["Log posts 1"] = "WWII Assets",
  ["Log posts 2"] = "WWII Assets",
  ["Log posts 3"] = "WWII Assets",
  ["Log ramps 1"] = "WWII Assets",
  ["Log ramps 2"] = "WWII Assets",
  ["Log ramps 3"] = "WWII Assets",
  ["M32-10C_01"] = "Massun92 Assets",
  ["M32-10C_02"] = "Massun92 Assets",
  ["M32-10C_03"] = "Massun92 Assets",
  ["M32-10C_04"] = "Massun92 Assets",
  ["M92_10Ft_Container"] = "C-130 Assets",
  ["M92_Ammo_Pallet"] = "C-130 Assets",
  ["M92_Concrete_Barrier_Cargo"] = "C-130 Assets",
  ["M92_MRE_Pallet"] = "C-130 Assets",
  ["MJ-1_01"] = "Massun92 Assets",
  ["MJ-1_02"] = "Massun92 Assets",
  ["NF-2_LightOff01"] = "Massun92 Assets",
  ["NF-2_LightOff02"] = "Massun92 Assets",
  ["NF-2_LightOn"] = "Massun92 Assets",
  ["Nodding_Donkey_Pump"] = "South Atlantic Assets",
  ["Oil Barrel"] = "Massun92 Assets",
  ["Oil rig"] = "Tech Weapon Pack",
  ["Orca"] = "South Atlantic Assets",
  ["P20_01"] = "Massun92 Assets",
  ["Pile of Woods"] = "Massun92 Assets",
  ["Revetment_x4"] = "Massun92 Assets",
  ["Revetment_x8"] = "Massun92 Assets",
  ["SA Ski Ramp"] = "South Atlantic Assets",
  ["SK_C_28_naval_gun"] = "WWII Assets",
  ["Sandbag_01"] = "Massun92 Assets",
  ["Sandbag_02"] = "Massun92 Assets",
  ["Sandbag_03"] = "Massun92 Assets",
  ["Sandbag_04"] = "Massun92 Assets",
  ["Sandbag_05"] = "Massun92 Assets",
  ["Sandbag_06"] = "Massun92 Assets",
  ["Sandbag_07"] = "Massun92 Assets",
  ["Sandbag_08"] = "Massun92 Assets",
  ["Sandbag_09"] = "Massun92 Assets",
  ["Sandbag_10"] = "Massun92 Assets",
  ["Sandbag_11"] = "Massun92 Assets",
  ["Sandbag_12"] = "Massun92 Assets",
  ["Sandbag_13"] = "Massun92 Assets",
  ["Sandbag_15"] = "Massun92 Assets",
  ["Sandbag_16"] = "Massun92 Assets",
  ["Sandbag_17"] = "Massun92 Assets",
  ["Shelter01"] = "Massun92 Assets",
  ["Shelter02"] = "Massun92 Assets",
  ["Siegfried Line"] = "WWII Assets",
  ["Ski Ramp"] = "South Atlantic Assets",
  ["Small_LightHouse"] = "South Atlantic Assets",
  ["Stanley_LightHouse"] = "South Atlantic Assets",
  ["Tent01"] = "Massun92 Assets",
  ["Tent02"] = "Massun92 Assets",
  ["Tent03"] = "Massun92 Assets",
  ["Tent04"] = "Massun92 Assets",
  ["Tent05"] = "Massun92 Assets",
  ["Tetrahydra"] = "WWII Assets",
  ["Toolbox01"] = "Massun92 Assets",
  ["Toolbox02"] = "Massun92 Assets",
  ["Tower Crane"] = "South Atlantic Assets",
  ["TugHarlan"] = "Massun92 Assets",
  ["Twall_x1"] = "Massun92 Assets",
  ["Twall_x6"] = "Massun92 Assets",
  ["Twall_x6_3mts"] = "Massun92 Assets",
  ["WindTurbine"] = "South Atlantic Assets",
  ["WindTurbine_11"] = "South Atlantic Assets",
  ["billboard_motorized"] = "South Atlantic Assets",
  ["cds_barrels"] = "C-130 Assets",
  ["cds_crate"] = "C-130 Assets",
  ["container_20ft"] = "Tech Weapon Pack",
  ["container_40ft"] = "Tech Weapon Pack",
  ["fire_control"] = "WWII Assets",
  ["l118"] = "South Atlantic Assets",
  ["m1_vla"] = "WWII Assets",
  ["offshore WindTurbine"] = "South Atlantic Assets",
  ["offshore WindTurbine2"] = "South Atlantic Assets",
  ["r11_volvo"] = "Massun92 Assets",
  ["us carrier shooter"] = "Supercarrier",
  ["us carrier tech"] = "Supercarrier",
  ["warning_board_a"] = "China Asset Pack",
  ["warning_board_b"] = "China Asset Pack",
}

---@param type_string string  DCS type-string to look up
---@return string|nil  asset-pack label if non-base, nil otherwise
sms.statics.origin_of = function(type_string)
  if type(type_string) ~= "string" then return nil end
  return _origin[type_string]
end
