-- AUTO-GENERATED by `dcs-sms gen-units`. Do not edit by hand.
-- Source: dcs-lua-datamine @   (regenerated 2026-04-30T15:53:55Z)
-- See docs/api/units.md for usage.

assert(type(sms) == "table",           "framework/sms.lua must be loaded first")
assert(type(sms.constants) == "table", "framework/constants.lua must be loaded first")
local log = sms.log.module("sms.constants.units")

---@alias sms.GroupSpawnType
---| "1L13 EWR"
---| "2B11 mortar"
---| "2S6 Tunguska"
---| "55G6 EWR"
---| "5p73 s-125 ln"
---| "A-10A"
---| "A-10C"
---| "A-10C_2"
---| "A-20G"
---| "A-50"
---| "A6E"
---| "AA8"
---| "AAV7"
---| "AH-1W"
---| "AH-64A"
---| "AH-64D"
---| "AH-64D_BLK_II"
---| "AJS37"
---| "ALBATROS"
---| "ATMZ-5"
---| "ATZ-10"
---| "ATZ-5"
---| "ATZ-60_Maz"
---| "AV8BNA"
---| "Allies_Director"
---| "An-26B"
---| "An-30M"
---| "B-17G"
---| "B-1B"
---| "B-52H"
---| "B600_drivable"
---| "BDK-775"
---| "BMD-1"
---| "BMP-1"
---| "BMP-2"
---| "BMP-3"
---| "BRDM-2"
---| "BRDM-2_malyutka"
---| "BTR-60"
---| "BTR-70"
---| "BTR-80"
---| "BTR-82A"
---| "BTR_D"
---| "Bedford_MWD"
---| "Bf-109K-4"
---| "Blitz_36-6700A"
---| "Boxcartrinity"
---| "Bunker"
---| "C-101CC"
---| "C-101EB"
---| "C-130"
---| "C-130J-30"
---| "C-17A"
---| "C-47"
---| "CCKW_353"
---| "CH-47D"
---| "CH-47Fbl1"
---| "CH-53E"
---| "CHAP_9K720_Cluster"
---| "CHAP_9K720_HE"
---| "CHAP_BMPT"
---| "CHAP_FV101"
---| "CHAP_FV107"
---| "CHAP_IRISTSLM_CP"
---| "CHAP_IRISTSLM_LN"
---| "CHAP_IRISTSLM_STR"
---| "CHAP_M1083"
---| "CHAP_M1130"
---| "CHAP_M142_ATACMS_M39A1"
---| "CHAP_M142_ATACMS_M48"
---| "CHAP_M142_GMLRS_M30"
---| "CHAP_M142_GMLRS_M31"
---| "CHAP_MATV"
---| "CHAP_PantsirS1"
---| "CHAP_Project22160"
---| "CHAP_Project22160_TorM2KM"
---| "CHAP_T64BV"
---| "CHAP_T84OplotM"
---| "CHAP_T90M"
---| "CHAP_TOS1A"
---| "CHAP_TigerUHT"
---| "CHAP_TorM2"
---| "CVN_71"
---| "CVN_72"
---| "CVN_73"
---| "CVN_75"
---| "CV_1143_5"
---| "CastleClass_01"
---| "Centaur_IV"
---| "Challenger2"
---| "Chieftain_mk3"
---| "Christen Eagle II"
---| "Churchill_VII"
---| "Coach a passenger"
---| "Coach a platform"
---| "Coach a tank blue"
---| "Coach a tank yellow"
---| "Coach cargo"
---| "Coach cargo open"
---| "Cobra"
---| "Cromwell_IV"
---| "DRG_Class_86"
---| "DR_50Ton_Flat_Wagon"
---| "Daimler_AC"
---| "Dog Ear radar"
---| "Dry-cargo ship-1"
---| "Dry-cargo ship-2"
---| "E-2C"
---| "E-3A"
---| "ELNYA"
---| "ES44AH"
---| "Electric locomotive"
---| "Elefant_SdKfz_184"
---| "Essex"
---| "F-117A"
---| "F-14A"
---| "F-14A-135-GR"
---| "F-14A-135-GR-Early"
---| "F-14B"
---| "F-15C"
---| "F-15E"
---| "F-15ESE"
---| "F-16A"
---| "F-16A MLU"
---| "F-16C bl.50"
---| "F-16C bl.52d"
---| "F-16C_50"
---| "F-4E"
---| "F-4E-45MC"
---| "F-5E"
---| "F-5E-3"
---| "F-5E-3_FC"
---| "F-86F Sabre"
---| "F-86F_FC"
---| "F/A-18A"
---| "F/A-18C"
---| "F4U-1D"
---| "F4U-1D_CW"
---| "FA-18C_hornet"
---| "FPS-117"
---| "FPS-117 Dome"
---| "FPS-117 ECS"
---| "FW-190A8"
---| "FW-190D9"
---| "Falcon_Gyrocopter"
---| "Flakscheinwerfer_37"
---| "Forrestal"
---| "FuMG-401"
---| "FuSe-65"
---| "GAZ-3307"
---| "GAZ-3308"
---| "GAZ-66"
---| "GD-20"
---| "GPS_Spoofer_Blue"
---| "GPS_Spoofer_Red"
---| "Gepard"
---| "German_covered_wagon_G10"
---| "German_tank_wagon"
---| "Grad-URAL"
---| "Grad_FDDM"
---| "H-6J"
---| "HEMTT TFFT"
---| "HEMTT_C-RAM_Phalanx"
---| "HL_B8M1"
---| "HL_DSHK"
---| "HL_KORD"
---| "HL_ZU-23"
---| "HQ-7_LN_P"
---| "HQ-7_LN_SP"
---| "HQ-7_STR_SP"
---| "HandyWind"
---| "HarborTug"
---| "Hawk"
---| "Hawk cwar"
---| "Hawk ln"
---| "Hawk pcp"
---| "Hawk sr"
---| "Hawk tr"
---| "Higgins_boat"
---| "Horch_901_typ_40_kfz_21"
---| "Hummer"
---| "I-16"
---| "IKARUS Bus"
---| "IL-76MD"
---| "IL-78M"
---| "IMPROVED_KILO"
---| "Igla manpad INS"
---| "Infantry AK"
---| "Infantry AK Ins"
---| "Infantry AK ver2"
---| "Infantry AK ver3"
---| "J-11A"
---| "JF-17"
---| "JTAC"
---| "JagdPz_IV"
---| "Jagdpanther_G1"
---| "Ju-88A4"
---| "KAMAZ Truck"
---| "KC-135"
---| "KC130"
---| "KC135MPRS"
---| "KDO_Mod40"
---| "KILO"
---| "KJ-2000"
---| "KS-19"
---| "KUZNECOW"
---| "Ka-27"
---| "Ka-50"
---| "Ka-50_3"
---| "KrAZ6322"
---| "Kub 1S91 str"
---| "Kub 2P25 ln"
---| "Kubelwagen_82"
---| "L-39C"
---| "L-39ZA"
---| "L118_Unit"
---| "LARC-V"
---| "LAV-25"
---| "LAZ Bus"
---| "LHA_Tarawa"
---| "LST_Mk2"
---| "La-7"
---| "La_Combattante_II"
---| "Land_Rover_101_FC"
---| "Land_Rover_109_S3"
---| "LeFH_18-40-105"
---| "Leclerc"
---| "Leopard-2"
---| "Leopard-2A5"
---| "Leopard1A3"
---| "LiAZ Bus"
---| "Locomotive"
---| "M 818"
---| "M-1 Abrams"
---| "M-109"
---| "M-113"
---| "M-2 Bradley"
---| "M-2000C"
---| "M-60"
---| "M1043 HMMWV Armament"
---| "M1045 HMMWV TOW"
---| "M1097 Avenger"
---| "M10_GMC"
---| "M1126 Stryker ICV"
---| "M1128 Stryker MGS"
---| "M1134 Stryker ATGM"
---| "M12_GMC"
---| "M1A2C_SEP_V3"
---| "M1_37mm"
---| "M2A1-105"
---| "M2A1_halftrack"
---| "M30_CC"
---| "M45_Quadmount"
---| "M48 Chaparral"
---| "M4A4_Sherman_FF"
---| "M4_Sherman"
---| "M4_Tractor"
---| "M6 Linebacker"
---| "M8_Greyhound"
---| "M978 HEMTT Tanker"
---| "MAZ-6303"
---| "MB-339A"
---| "MB-339APAN"
---| "MCV-80"
---| "MJ-1_drivable"
---| "MLRS"
---| "MLRS FDDM"
---| "MOLNIYA"
---| "MOSCOW"
---| "MQ-9 Reaper"
---| "MTLB"
---| "Marder"
---| "Maschinensatz_33"
---| "MaxxPro_MRAP"
---| "Merkava_Mk4"
---| "Mi-24P"
---| "Mi-24V"
---| "Mi-26"
---| "Mi-28N"
---| "Mi-8MT"
---| "MiG-15bis"
---| "MiG-15bis_FC"
---| "MiG-19P"
---| "MiG-21Bis"
---| "MiG-23MLD"
---| "MiG-25PD"
---| "MiG-25RBT"
---| "MiG-27K"
---| "MiG-29 Fulcrum"
---| "MiG-29A"
---| "MiG-29G"
---| "MiG-29S"
---| "MiG-31"
---| "Mirage 2000-5"
---| "Mirage-F1AD"
---| "Mirage-F1AZ"
---| "Mirage-F1B"
---| "Mirage-F1BD"
---| "Mirage-F1BE"
---| "Mirage-F1BQ"
---| "Mirage-F1C"
---| "Mirage-F1C-200"
---| "Mirage-F1CE"
---| "Mirage-F1CG"
---| "Mirage-F1CH"
---| "Mirage-F1CJ"
---| "Mirage-F1CK"
---| "Mirage-F1CR"
---| "Mirage-F1CT"
---| "Mirage-F1CZ"
---| "Mirage-F1DDA"
---| "Mirage-F1ED"
---| "Mirage-F1EDA"
---| "Mirage-F1EE"
---| "Mirage-F1EH"
---| "Mirage-F1EQ"
---| "Mirage-F1JA"
---| "Mirage-F1M-CE"
---| "Mirage-F1M-EE"
---| "MosquitoFBMkVI"
---| "NASAMS_Command_Post"
---| "NASAMS_LN_B"
---| "NASAMS_LN_C"
---| "NASAMS_Radar_MPQ64F1"
---| "NEUSTRASH"
---| "OH-58D"
---| "OH58D"
---| "Osa 9A33 ln"
---| "P-47D-30"
---| "P-47D-30bl1"
---| "P-47D-40"
---| "P-51D"
---| "P-51D-30-NA"
---| "P14_SR"
---| "P20_drivable"
---| "PERRY"
---| "PIOTR"
---| "PL5EII Loadout"
---| "PL8 Loadout"
---| "PLZ05"
---| "PT_76"
---| "Pak40"
---| "Paratrooper AKS-74"
---| "Paratrooper RPG-16"
---| "Patriot AMG"
---| "Patriot ECS"
---| "Patriot EPP"
---| "Patriot cp"
---| "Patriot ln"
---| "Patriot str"
---| "Predator GCS"
---| "Predator TrojanSpirit"
---| "Pz_IV_H"
---| "Pz_V_Panther_G"
---| "QF-4E"
---| "QF_37_AA"
---| "RD_75"
---| "REZKY"
---| "RLS_19J6"
---| "RPC_5N62V"
---| "RQ-1A Predator"
---| "Roland ADS"
---| "Roland Radar"
---| "S-200_Launcher"
---| "S-300PS 40B6M tr"
---| "S-300PS 40B6MD sr"
---| "S-300PS 40B6MD sr_19J6"
---| "S-300PS 54K6 cp"
---| "S-300PS 5H63C 30H6_tr"
---| "S-300PS 5P85C ln"
---| "S-300PS 5P85D ln"
---| "S-300PS 64H6E sr"
---| "S-3B"
---| "S-3B Tanker"
---| "S-60_Type59_Artillery"
---| "SA-11 Buk CC 9S470M1"
---| "SA-11 Buk LN 9A310M1"
---| "SA-11 Buk SR 9S18M1"
---| "SA-18 Igla comm"
---| "SA-18 Igla manpad"
---| "SA-18 Igla-S comm"
---| "SA-18 Igla-S manpad"
---| "SA342L"
---| "SA342M"
---| "SA342Minigun"
---| "SA342Mistral"
---| "SAU 2-C9"
---| "SAU Akatsia"
---| "SAU Gvozdika"
---| "SAU Msta"
---| "SD10 Loadout"
---| "SH-3W"
---| "SH-60B"
---| "SKP-11"
---| "SK_C_28_naval_gun"
---| "SNR_75V"
---| "SOM"
---| "SON_9"
---| "S_75M_Volhov"
---| "S_75_ZIL"
---| "Sandbox"
---| "Schnellboot_type_S130"
---| "Scud_B"
---| "Sd_Kfz_2"
---| "Sd_Kfz_234_2_Puma"
---| "Sd_Kfz_251"
---| "Sd_Kfz_7"
---| "Seawise_Giant"
---| "Ship_Tilde_Supply"
---| "Silkworm_SR"
---| "Smerch"
---| "Smerch_HE"
---| "Soldier AK"
---| "Soldier M249"
---| "Soldier M4"
---| "Soldier M4 GRG"
---| "Soldier RPG"
---| "Soldier stinger"
---| "SpGH_Dana"
---| "SpitfireLFMkIX"
---| "SpitfireLFMkIXCW"
---| "Stennis"
---| "Stinger comm"
---| "Stinger comm dsr"
---| "Strela-1 9P31"
---| "Strela-10M3"
---| "Stug_III"
---| "Stug_IV"
---| "SturmPzIV"
---| "Su-17M4"
---| "Su-24M"
---| "Su-24MR"
---| "Su-25"
---| "Su-25T"
---| "Su-25TM"
---| "Su-27"
---| "Su-30"
---| "Su-33"
---| "Su-34"
---| "Suidae"
---| "T-34-85"
---| "T-55"
---| "T-72B"
---| "T-72B3"
---| "T-80B"
---| "T-80UD"
---| "T-90"
---| "T155_Firtina"
---| "T62M"
---| "TACAN_beacon"
---| "TF-51D"
---| "TICONDEROG"
---| "TPZ"
---| "TYPE-59"
---| "TZ-22_KrAZ"
---| "Tankcartrinity"
---| "Tetrarch"
---| "Tiger_I"
---| "Tiger_II_H"
---| "Tigr_233036"
---| "Tor 9A331"
---| "Tornado GR4"
---| "Tornado IDS"
---| "Train"
---| "Trolley bus"
---| "Tu-142"
---| "Tu-160"
---| "Tu-22M3"
---| "Tu-95MS"
---| "TugHarlan_drivable"
---| "Type_021_1"
---| "Type_052B"
---| "Type_052C"
---| "Type_054A"
---| "Type_071"
---| "Type_093"
---| "Type_3_80mm_AA"
---| "Type_88_75mm_AA"
---| "Type_89_I_Go"
---| "Type_94_25mm_AA_Truck"
---| "Type_94_Truck"
---| "Type_96_25mm_AA"
---| "Type_98_Ke_Ni"
---| "Type_98_So_Da"
---| "UAZ-469"
---| "UH-1H"
---| "UH-60A"
---| "USS_Arleigh_Burke_IIa"
---| "USS_Samuel_Chase"
---| "Uboat_VIIC"
---| "Uragan_BM-27"
---| "Ural ATsP-6"
---| "Ural-375"
---| "Ural-375 PBU"
---| "Ural-375 ZU-23"
---| "Ural-375 ZU-23 Insurgent"
---| "Ural-4320 APA-5D"
---| "Ural-4320-31"
---| "Ural-4320T"
---| "VAB_Mephisto"
---| "VAZ Car"
---| "VINSON"
---| "Vulcan"
---| "Wellcarnsc"
---| "Wespe124"
---| "Willys_MB"
---| "WingLoong-I"
---| "Yak-40"
---| "Yak-52"
---| "ZBD04A"
---| "ZIL-131 KUNG"
---| "ZIL-135"
---| "ZIL-4331"
---| "ZSU-23-4 Shilka"
---| "ZSU_57_2"
---| "ZTZ96B"
---| "ZU-23 Closed Insurgent"
---| "ZU-23 Emplacement"
---| "ZU-23 Emplacement Closed"
---| "ZU-23 Insurgent"
---| "ZWEZDNY"
---| "ZiL-131 APA-80"
---| "ara_vdm"
---| "atconveyor"
---| "bofors40"
---| "fire_control"
---| "flak18"
---| "flak30"
---| "flak36"
---| "flak37"
---| "flak38"
---| "flak41"
---| "gaz-66_civil"
---| "generator_5i57"
---| "hms_invincible"
---| "house1arm"
---| "house2arm"
---| "houseA_arm"
---| "hy_launcher"
---| "kamaz_tent_civil"
---| "leander-gun-achilles"
---| "leander-gun-andromeda"
---| "leander-gun-ariadne"
---| "leander-gun-condell"
---| "leander-gun-lynch"
---| "leopard-2A4"
---| "leopard-2A4_trs"
---| "outpost"
---| "outpost_road"
---| "outpost_road_l"
---| "outpost_road_r"
---| "p-19 s-125 sr"
---| "prmg_gp_beacon"
---| "prmg_loc_beacon"
---| "r11_volvo_drivable"
---| "rapier_fsa_blindfire_radar"
---| "rapier_fsa_launcher"
---| "rapier_fsa_optical_tracker_unit"
---| "rsbn_beacon"
---| "santafe"
---| "snr s-125 tr"
---| "soldier_mauser98"
---| "soldier_wwii_br_01"
---| "soldier_wwii_us"
---| "speedboat"
---| "tacr2a"
---| "tt_B8M1"
---| "tt_DSHK"
---| "tt_KORD"
---| "tt_ZU-23"
---| "ural_4230_civil_b"
---| "ural_4230_civil_t"
---| "ural_atz5_civil"
---| "v1_launcher"
---| "zil-131_civil"

---@class sms.constants.units
sms.constants.units = sms.constants.units or {}

sms.constants.units.air_defence = {
  aaa = {
    Allies_Director = "Allies_Director",                     -- WWII Assets
    CHAP_PantsirS1 = "CHAP_PantsirS1",                       -- Currenthill Assets
    Flakscheinwerfer_37 = "Flakscheinwerfer_37",             -- WWII Assets
    Gepard = "Gepard",
    HEMTT_C_RAM_Phalanx = "HEMTT_C-RAM_Phalanx",             -- Heavy Metal
    HL_ZU_23 = "HL_ZU-23",                                   -- Tech Weapon Pack
    KDO_Mod40 = "KDO_Mod40",                                 -- WWII Assets
    KS_19 = "KS-19",                                         -- Tech Weapon Pack
    M1097_Avenger = "M1097 Avenger",
    M1_37mm = "M1_37mm",                                     -- WWII Assets
    M45_Quadmount = "M45_Quadmount",                         -- WWII Assets
    M6_Linebacker = "M6 Linebacker",
    QF_37_AA = "QF_37_AA",                                   -- WWII Assets
    SON_9 = "SON_9",                                         -- Tech Weapon Pack
    S_60_Type59_Artillery = "S-60_Type59_Artillery",         -- Tech Weapon Pack
    Type_3_80mm_AA = "Type_3_80mm_AA",                       -- WWII Assets
    Type_88_75mm_AA = "Type_88_75mm_AA",                     -- WWII Assets
    Type_94_25mm_AA_Truck = "Type_94_25mm_AA_Truck",         -- WWII Assets
    Type_96_25mm_AA = "Type_96_25mm_AA",                     -- WWII Assets
    Ural_375_ZU_23 = "Ural-375 ZU-23",
    Ural_375_ZU_23_Insurgent = "Ural-375 ZU-23 Insurgent",
    Vulcan = "Vulcan",
    ZSU_23_4_Shilka = "ZSU-23-4 Shilka",
    ZSU_57_2 = "ZSU_57_2",                                   -- Tech Weapon Pack
    ZU_23_Closed_Insurgent = "ZU-23 Closed Insurgent",
    ZU_23_Emplacement = "ZU-23 Emplacement",
    ZU_23_Emplacement_Closed = "ZU-23 Emplacement Closed",
    ZU_23_Insurgent = "ZU-23 Insurgent",
    _2S6_Tunguska = "2S6 Tunguska",
    bofors40 = "bofors40",                                   -- Tech Weapon Pack
    flak18 = "flak18",                                       -- Tech Weapon Pack
    flak30 = "flak30",                                       -- WWII Assets
    flak36 = "flak36",                                       -- WWII Assets
    flak37 = "flak37",                                       -- WWII Assets
    flak38 = "flak38",                                       -- WWII Assets
    flak41 = "flak41",                                       -- WWII Assets
    tt_ZU_23 = "tt_ZU-23",                                   -- Tech Weapon Pack
  },
  manpads = {
    Igla_manpad_INS = "Igla manpad INS",
    SA_18_Igla_S_comm = "SA-18 Igla-S comm",
    SA_18_Igla_S_manpad = "SA-18 Igla-S manpad",
    SA_18_Igla_comm = "SA-18 Igla comm",
    SA_18_Igla_manpad = "SA-18 Igla manpad",
    Soldier_stinger = "Soldier stinger",
    Stinger_comm = "Stinger comm",
    Stinger_comm_dsr = "Stinger comm dsr",
  },
  misc = {
    CHAP_IRISTSLM_CP = "CHAP_IRISTSLM_CP",                   -- Currenthill Assets
    FPS_117_ECS = "FPS-117 ECS",                             -- Tech Weapon Pack
    Hawk_pcp = "Hawk pcp",
    Maschinensatz_33 = "Maschinensatz_33",                   -- WWII Assets
    NASAMS_Command_Post = "NASAMS_Command_Post",             -- Tech Weapon Pack
    Patriot_AMG = "Patriot AMG",
    Patriot_ECS = "Patriot ECS",
    Patriot_EPP = "Patriot EPP",
    Patriot_cp = "Patriot cp",
    SA_11_Buk_CC_9S470M1 = "SA-11 Buk CC 9S470M1",
    S_300PS_54K6_cp = "S-300PS 54K6 cp",                     -- Heavy Metal
    generator_5i57 = "generator_5i57",                       -- Tech Weapon Pack
  },
  radar = {
    FPS_117 = "FPS-117",                                     -- Tech Weapon Pack
    FPS_117_Dome = "FPS-117 Dome",                           -- Tech Weapon Pack
    FuMG_401 = "FuMG-401",                                   -- WWII Assets
    FuSe_65 = "FuSe-65",                                     -- WWII Assets
    _1L13_EWR = "1L13 EWR",
    _55G6_EWR = "55G6 EWR",
  },
  sam = {
    CHAP_IRISTSLM_LN = "CHAP_IRISTSLM_LN",                   -- Currenthill Assets
    CHAP_IRISTSLM_STR = "CHAP_IRISTSLM_STR",                 -- Currenthill Assets
    CHAP_TorM2 = "CHAP_TorM2",                               -- Currenthill Assets
    Dog_Ear_radar = "Dog Ear radar",
    HQ_7_LN_P = "HQ-7_LN_P",                                 -- China Asset Pack
    HQ_7_LN_SP = "HQ-7_LN_SP",                               -- China Asset Pack
    HQ_7_STR_SP = "HQ-7_STR_SP",                             -- China Asset Pack
    Hawk_cwar = "Hawk cwar",
    Hawk_ln = "Hawk ln",
    Hawk_sr = "Hawk sr",
    Hawk_tr = "Hawk tr",
    Kub_1S91_str = "Kub 1S91 str",
    Kub_2P25_ln = "Kub 2P25 ln",
    M48_Chaparral = "M48 Chaparral",
    NASAMS_LN_B = "NASAMS_LN_B",                             -- Tech Weapon Pack
    NASAMS_LN_C = "NASAMS_LN_C",                             -- Tech Weapon Pack
    NASAMS_Radar_MPQ64F1 = "NASAMS_Radar_MPQ64F1",           -- Tech Weapon Pack
    Osa_9A33_ln = "Osa 9A33 ln",
    P14_SR = "P14_SR",                                       -- Cold War Asset Pack
    Patriot_ln = "Patriot ln",
    Patriot_str = "Patriot str",
    RD_75 = "RD_75",                                         -- Tech Weapon Pack
    RLS_19J6 = "RLS_19J6",                                   -- Tech Weapon Pack
    RPC_5N62V = "RPC_5N62V",                                 -- Tech Weapon Pack
    Roland_ADS = "Roland ADS",
    Roland_Radar = "Roland Radar",
    SA_11_Buk_LN_9A310M1 = "SA-11 Buk LN 9A310M1",
    SA_11_Buk_SR_9S18M1 = "SA-11 Buk SR 9S18M1",
    SNR_75V = "SNR_75V",                                     -- Tech Weapon Pack
    S_200_Launcher = "S-200_Launcher",                       -- Tech Weapon Pack
    S_300PS_40B6MD_sr = "S-300PS 40B6MD sr",                 -- Heavy Metal
    S_300PS_40B6MD_sr_19J6 = "S-300PS 40B6MD sr_19J6",       -- Heavy Metal
    S_300PS_40B6M_tr = "S-300PS 40B6M tr",                   -- Heavy Metal
    S_300PS_5H63C_30H6_tr = "S-300PS 5H63C 30H6_tr",         -- Heavy Metal
    S_300PS_5P85C_ln = "S-300PS 5P85C ln",                   -- Heavy Metal
    S_300PS_5P85D_ln = "S-300PS 5P85D ln",                   -- Heavy Metal
    S_300PS_64H6E_sr = "S-300PS 64H6E sr",                   -- Heavy Metal
    S_75M_Volhov = "S_75M_Volhov",                           -- Tech Weapon Pack
    Strela_10M3 = "Strela-10M3",
    Strela_1_9P31 = "Strela-1 9P31",                         -- Cold War Asset Pack
    Tor_9A331 = "Tor 9A331",
    _5p73_s_125_ln = "5p73 s-125 ln",
    p_19_s_125_sr = "p-19 s-125 sr",
    rapier_fsa_blindfire_radar = "rapier_fsa_blindfire_radar", -- Tech Weapon Pack
    rapier_fsa_launcher = "rapier_fsa_launcher",             -- Tech Weapon Pack
    rapier_fsa_optical_tracker_unit = "rapier_fsa_optical_tracker_unit", -- Tech Weapon Pack
    snr_s_125_tr = "snr s-125 tr",
  },
}

sms.constants.units.armor = {
  apc = {
    AAV7 = "AAV7",
    BRDM_2 = "BRDM-2",                                       -- Cold War Asset Pack
    BTR_60 = "BTR-60",                                       -- Cold War Asset Pack
    BTR_70 = "BTR-70",                                       -- Cold War Asset Pack
    BTR_80 = "BTR-80",                                       -- Tech Weapon Pack
    BTR_82A = "BTR-82A",                                     -- Tech Weapon Pack
    BTR_D = "BTR_D",
    CHAP_FV107 = "CHAP_FV107",                               -- Currenthill Assets
    CHAP_M1130 = "CHAP_M1130",                               -- Currenthill Assets
    CHAP_MATV = "CHAP_MATV",                                 -- Currenthill Assets
    Cobra = "Cobra",
    HL_DSHK = "HL_DSHK",                                     -- Tech Weapon Pack
    HL_KORD = "HL_KORD",                                     -- Tech Weapon Pack
    LAV_25 = "LAV-25",
    M1043_HMMWV_Armament = "M1043 HMMWV Armament",
    M1045_HMMWV_TOW = "M1045 HMMWV TOW",
    M1126_Stryker_ICV = "M1126 Stryker ICV",
    M2A1_halftrack = "M2A1_halftrack",                       -- Tech Weapon Pack
    MCV_80 = "MCV-80",
    MTLB = "MTLB",
    M_113 = "M-113",
    MaxxPro_MRAP = "MaxxPro_MRAP",                           -- Heavy Metal
    Sd_Kfz_251 = "Sd_Kfz_251",                               -- Tech Weapon Pack
    TPZ = "TPZ",
    tt_DSHK = "tt_DSHK",                                     -- Tech Weapon Pack
    tt_KORD = "tt_KORD",                                     -- Tech Weapon Pack
  },
  ifv = {
    BMD_1 = "BMD-1",
    BMP_1 = "BMP-1",
    BMP_2 = "BMP-2",
    BMP_3 = "BMP-3",
    BRDM_2_malyutka = "BRDM-2_malyutka",                     -- Cold War Asset Pack
    CHAP_BMPT = "CHAP_BMPT",                                 -- Currenthill Assets
    Daimler_AC = "Daimler_AC",                               -- WWII Assets
    M1134_Stryker_ATGM = "M1134 Stryker ATGM",
    M4_Tractor = "M4_Tractor",                               -- WWII Assets
    M8_Greyhound = "M8_Greyhound",                           -- WWII Assets
    M_2_Bradley = "M-2 Bradley",
    Marder = "Marder",
    Sd_Kfz_234_2_Puma = "Sd_Kfz_234_2_Puma",                 -- WWII Assets
    Tetrarch = "Tetrarch",                                   -- WWII Assets
    VAB_Mephisto = "VAB_Mephisto",                           -- Tech Weapon Pack
    ZBD04A = "ZBD04A",                                       -- China Asset Pack
  },
  misc = {
    SturmPzIV = "SturmPzIV",                                 -- WWII Assets
  },
  tanks = {
    CHAP_FV101 = "CHAP_FV101",                               -- Currenthill Assets
    CHAP_T64BV = "CHAP_T64BV",                               -- Currenthill Assets
    CHAP_T84OplotM = "CHAP_T84OplotM",                       -- Currenthill Assets
    CHAP_T90M = "CHAP_T90M",                                 -- Currenthill Assets
    Centaur_IV = "Centaur_IV",                               -- WWII Assets
    Challenger2 = "Challenger2",
    Chieftain_mk3 = "Chieftain_mk3",                         -- Tech Weapon Pack
    Churchill_VII = "Churchill_VII",                         -- WWII Assets
    Cromwell_IV = "Cromwell_IV",                             -- WWII Assets
    Elefant_SdKfz_184 = "Elefant_SdKfz_184",                 -- WWII Assets
    JagdPz_IV = "JagdPz_IV",                                 -- WWII Assets
    Jagdpanther_G1 = "Jagdpanther_G1",                       -- WWII Assets
    Leclerc = "Leclerc",
    Leopard1A3 = "Leopard1A3",
    Leopard_2 = "Leopard-2",                                 -- Tech Weapon Pack
    Leopard_2A5 = "Leopard-2A5",                             -- Tech Weapon Pack
    M10_GMC = "M10_GMC",                                     -- WWII Assets
    M1128_Stryker_MGS = "M1128 Stryker MGS",
    M1A2C_SEP_V3 = "M1A2C_SEP_V3",                           -- Heavy Metal
    M4A4_Sherman_FF = "M4A4_Sherman_FF",                     -- WWII Assets
    M4_Sherman = "M4_Sherman",                               -- Tech Weapon Pack
    M_1_Abrams = "M-1 Abrams",                               -- Heavy Metal
    M_60 = "M-60",
    Merkava_Mk4 = "Merkava_Mk4",
    PT_76 = "PT_76",                                         -- Tech Weapon Pack
    Pz_IV_H = "Pz_IV_H",                                     -- Tech Weapon Pack
    Pz_V_Panther_G = "Pz_V_Panther_G",                       -- WWII Assets
    Stug_III = "Stug_III",                                   -- WWII Assets
    Stug_IV = "Stug_IV",                                     -- WWII Assets
    T62M = "T62M",                                           -- Cold War Asset Pack
    TYPE_59 = "TYPE-59",                                     -- China Asset Pack
    T_34_85 = "T-34-85",                                     -- Cold War Asset Pack
    T_55 = "T-55",
    T_72B = "T-72B",
    T_72B3 = "T-72B3",                                       -- Tech Weapon Pack
    T_80B = "T-80B",                                         -- Cold War Asset Pack
    T_80UD = "T-80UD",
    T_90 = "T-90",                                           -- Currenthill Assets
    Tiger_I = "Tiger_I",                                     -- WWII Assets
    Tiger_II_H = "Tiger_II_H",                               -- WWII Assets
    Type_89_I_Go = "Type_89_I_Go",                           -- WWII Assets
    Type_98_Ke_Ni = "Type_98_Ke_Ni",                         -- WWII Assets
    ZTZ96B = "ZTZ96B",                                       -- China Asset Pack
    leopard_2A4 = "leopard-2A4",                             -- Tech Weapon Pack
    leopard_2A4_trs = "leopard-2A4_trs",                     -- Tech Weapon Pack
  },
}

sms.constants.units.artillery = {
  CHAP_M142_ATACMS_M39A1 = "CHAP_M142_ATACMS_M39A1",         -- Currenthill Assets
  CHAP_M142_ATACMS_M48 = "CHAP_M142_ATACMS_M48",             -- Currenthill Assets
  CHAP_M142_GMLRS_M30 = "CHAP_M142_GMLRS_M30",               -- Currenthill Assets
  CHAP_M142_GMLRS_M31 = "CHAP_M142_GMLRS_M31",               -- Currenthill Assets
  CHAP_TOS1A = "CHAP_TOS1A",                                 -- Currenthill Assets
  Grad_FDDM = "Grad_FDDM",
  Grad_URAL = "Grad-URAL",
  HL_B8M1 = "HL_B8M1",                                       -- Tech Weapon Pack
  L118_Unit = "L118_Unit",                                   -- South Atlantic Assets
  LeFH_18_40_105 = "LeFH_18-40-105",                         -- WWII Assets
  M12_GMC = "M12_GMC",                                       -- WWII Assets
  M2A1_105 = "M2A1-105",                                     -- WWII Assets
  MLRS = "MLRS",
  MLRS_FDDM = "MLRS FDDM",
  M_109 = "M-109",
  PLZ05 = "PLZ05",                                           -- China Asset Pack
  Pak40 = "Pak40",                                           -- WWII Assets
  SAU_2_C9 = "SAU 2-C9",
  SAU_Akatsia = "SAU Akatsia",
  SAU_Gvozdika = "SAU Gvozdika",
  SAU_Msta = "SAU Msta",
  Smerch = "Smerch",
  Smerch_HE = "Smerch_HE",
  SpGH_Dana = "SpGH_Dana",
  T155_Firtina = "T155_Firtina",                             -- Tech Weapon Pack
  Uragan_BM_27 = "Uragan_BM-27",
  Wespe124 = "Wespe124",                                     -- WWII Assets
  _2B11_mortar = "2B11 mortar",
  tt_B8M1 = "tt_B8M1",                                       -- Tech Weapon Pack
}

sms.constants.units.fortifications = {
  Bunker = "Bunker",
  SK_C_28_naval_gun = "SK_C_28_naval_gun",                   -- WWII Assets
  Sandbox = "Sandbox",
  TACAN_beacon = "TACAN_beacon",
  fire_control = "fire_control",                             -- WWII Assets
  house1arm = "house1arm",
  house2arm = "house2arm",
  houseA_arm = "houseA_arm",
  outpost = "outpost",
  outpost_road = "outpost_road",
  outpost_road_l = "outpost_road_l",
  outpost_road_r = "outpost_road_r",
}

sms.constants.units.helicopters = {
  AH_1W = "AH-1W",
  AH_64A = "AH-64A",
  AH_64D = "AH-64D",
  AH_64D_BLK_II = "AH-64D_BLK_II",
  CHAP_TigerUHT = "CHAP_TigerUHT",                           -- Currenthill Assets
  CH_47D = "CH-47D",
  CH_47Fbl1 = "CH-47Fbl1",
  CH_53E = "CH-53E",
  Ka_27 = "Ka-27",
  Ka_50 = "Ka-50",
  Ka_50_3 = "Ka-50_3",
  Mi_24P = "Mi-24P",
  Mi_24V = "Mi-24V",
  Mi_26 = "Mi-26",
  Mi_28N = "Mi-28N",                                         -- Currenthill Assets
  Mi_8MT = "Mi-8MT",
  OH58D = "OH58D",
  OH_58D = "OH-58D",
  SA342L = "SA342L",
  SA342M = "SA342M",
  SA342Minigun = "SA342Minigun",
  SA342Mistral = "SA342Mistral",
  SH_3W = "SH-3W",
  SH_60B = "SH-60B",
  UH_1H = "UH-1H",
  UH_60A = "UH-60A",
}

sms.constants.units.infantry = {
  Infantry_AK = "Infantry AK",
  Infantry_AK_Ins = "Infantry AK Ins",
  Infantry_AK_ver2 = "Infantry AK ver2",
  Infantry_AK_ver3 = "Infantry AK ver3",
  JTAC = "JTAC",
  Paratrooper_AKS_74 = "Paratrooper AKS-74",
  Paratrooper_RPG_16 = "Paratrooper RPG-16",
  Soldier_AK = "Soldier AK",
  Soldier_M249 = "Soldier M249",
  Soldier_M4 = "Soldier M4",
  Soldier_M4_GRG = "Soldier M4 GRG",
  Soldier_RPG = "Soldier RPG",
  soldier_mauser98 = "soldier_mauser98",                     -- WWII Assets
  soldier_wwii_br_01 = "soldier_wwii_br_01",                 -- WWII Assets
  soldier_wwii_us = "soldier_wwii_us",                       -- WWII Assets
}

sms.constants.units.missiles = {
  CHAP_9K720_Cluster = "CHAP_9K720_Cluster",                 -- Currenthill Assets
  CHAP_9K720_HE = "CHAP_9K720_HE",                           -- Currenthill Assets
  PL5EII_Loadout = "PL5EII Loadout",                         -- China Asset Pack
  PL8_Loadout = "PL8 Loadout",                               -- China Asset Pack
  SD10_Loadout = "SD10 Loadout",                             -- China Asset Pack
  Scud_B = "Scud_B",                                         -- Tech Weapon Pack
  Silkworm_SR = "Silkworm_SR",                               -- Tech Weapon Pack
  hy_launcher = "hy_launcher",                               -- Tech Weapon Pack
  v1_launcher = "v1_launcher",                               -- WWII Assets
}

sms.constants.units.planes = {
  A6E = "A6E",
  AJS37 = "AJS37",
  AV8BNA = "AV8BNA",
  A_10A = "A-10A",
  A_10C = "A-10C",
  A_10C_2 = "A-10C_2",
  A_20G = "A-20G",                                           -- WWII Assets
  A_50 = "A-50",
  An_26B = "An-26B",
  An_30M = "An-30M",
  B_17G = "B-17G",                                           -- WWII Assets
  B_1B = "B-1B",                                             -- Heavy Metal
  B_52H = "B-52H",                                           -- Heavy Metal
  Bf_109K_4 = "Bf-109K-4",                                   -- WWII Assets
  C_101CC = "C-101CC",
  C_101EB = "C-101EB",
  C_130 = "C-130",
  C_130J_30 = "C-130J-30",                                   -- C-130 Assets
  C_17A = "C-17A",
  C_47 = "C-47",                                             -- WWII Assets
  Christen_Eagle_II = "Christen Eagle II",
  E_2C = "E-2C",
  E_3A = "E-3A",
  F4U_1D = "F4U-1D",
  F4U_1D_CW = "F4U-1D_CW",
  FA_18C_hornet = "FA-18C_hornet",
  FW_190A8 = "FW-190A8",                                     -- WWII Assets
  FW_190D9 = "FW-190D9",                                     -- WWII Assets
  F_117A = "F-117A",
  F_14A = "F-14A",
  F_14A_135_GR = "F-14A-135-GR",
  F_14A_135_GR_Early = "F-14A-135-GR-Early",
  F_14B = "F-14B",
  F_15C = "F-15C",
  F_15E = "F-15E",
  F_15ESE = "F-15ESE",
  F_16A = "F-16A",
  F_16A_MLU = "F-16A MLU",
  F_16C_50 = "F-16C_50",
  F_16C_bl_50 = "F-16C bl.50",
  F_16C_bl_52d = "F-16C bl.52d",
  F_4E = "F-4E",
  F_4E_45MC = "F-4E-45MC",
  F_5E = "F-5E",
  F_5E_3 = "F-5E-3",
  F_5E_3_FC = "F-5E-3_FC",
  F_86F_FC = "F-86F_FC",
  F_86F_Sabre = "F-86F Sabre",
  F_A_18A = "F/A-18A",
  F_A_18C = "F/A-18C",
  Falcon_Gyrocopter = "Falcon_Gyrocopter",                   -- China Asset Pack
  H_6J = "H-6J",                                             -- China Asset Pack
  Hawk = "Hawk",
  IL_76MD = "IL-76MD",
  IL_78M = "IL-78M",
  I_16 = "I-16",
  JF_17 = "JF-17",                                           -- China Asset Pack
  J_11A = "J-11A",                                           -- China Asset Pack
  Ju_88A4 = "Ju-88A4",                                       -- WWII Assets
  KC130 = "KC130",
  KC135MPRS = "KC135MPRS",
  KC_135 = "KC-135",
  KJ_2000 = "KJ-2000",                                       -- China Asset Pack
  L_39C = "L-39C",
  L_39ZA = "L-39ZA",
  La_7 = "La-7",
  MB_339A = "MB-339A",
  MB_339APAN = "MB-339APAN",
  MQ_9_Reaper = "MQ-9 Reaper",
  M_2000C = "M-2000C",
  MiG_15bis = "MiG-15bis",
  MiG_15bis_FC = "MiG-15bis_FC",
  MiG_19P = "MiG-19P",
  MiG_21Bis = "MiG-21Bis",
  MiG_23MLD = "MiG-23MLD",
  MiG_25PD = "MiG-25PD",
  MiG_25RBT = "MiG-25RBT",
  MiG_27K = "MiG-27K",
  MiG_29A = "MiG-29A",
  MiG_29G = "MiG-29G",
  MiG_29S = "MiG-29S",
  MiG_29_Fulcrum = "MiG-29 Fulcrum",
  MiG_31 = "MiG-31",
  Mirage_2000_5 = "Mirage 2000-5",
  Mirage_F1AD = "Mirage-F1AD",                               -- Mirage F1 Assets
  Mirage_F1AZ = "Mirage-F1AZ",                               -- Mirage F1 Assets
  Mirage_F1B = "Mirage-F1B",                                 -- Mirage F1 Assets
  Mirage_F1BD = "Mirage-F1BD",                               -- Mirage F1 Assets
  Mirage_F1BE = "Mirage-F1BE",                               -- Mirage F1 Assets
  Mirage_F1BQ = "Mirage-F1BQ",                               -- Mirage F1 Assets
  Mirage_F1C = "Mirage-F1C",                                 -- Mirage F1 Assets
  Mirage_F1CE = "Mirage-F1CE",                               -- Mirage F1 Assets
  Mirage_F1CG = "Mirage-F1CG",                               -- Mirage F1 Assets
  Mirage_F1CH = "Mirage-F1CH",                               -- Mirage F1 Assets
  Mirage_F1CJ = "Mirage-F1CJ",                               -- Mirage F1 Assets
  Mirage_F1CK = "Mirage-F1CK",                               -- Mirage F1 Assets
  Mirage_F1CR = "Mirage-F1CR",                               -- Mirage F1 Assets
  Mirage_F1CT = "Mirage-F1CT",                               -- Mirage F1 Assets
  Mirage_F1CZ = "Mirage-F1CZ",                               -- Mirage F1 Assets
  Mirage_F1C_200 = "Mirage-F1C-200",                         -- Mirage F1 Assets
  Mirage_F1DDA = "Mirage-F1DDA",                             -- Mirage F1 Assets
  Mirage_F1ED = "Mirage-F1ED",                               -- Mirage F1 Assets
  Mirage_F1EDA = "Mirage-F1EDA",                             -- Mirage F1 Assets
  Mirage_F1EE = "Mirage-F1EE",                               -- Mirage F1 Assets
  Mirage_F1EH = "Mirage-F1EH",                               -- Mirage F1 Assets
  Mirage_F1EQ = "Mirage-F1EQ",                               -- Mirage F1 Assets
  Mirage_F1JA = "Mirage-F1JA",                               -- Mirage F1 Assets
  Mirage_F1M_CE = "Mirage-F1M-CE",                           -- Mirage F1 Assets
  Mirage_F1M_EE = "Mirage-F1M-EE",                           -- Mirage F1 Assets
  MosquitoFBMkVI = "MosquitoFBMkVI",                         -- WWII Assets
  P_47D_30 = "P-47D-30",                                     -- WWII Assets
  P_47D_30bl1 = "P-47D-30bl1",                               -- WWII Assets
  P_47D_40 = "P-47D-40",                                     -- WWII Assets
  P_51D = "P-51D",                                           -- WWII Assets
  P_51D_30_NA = "P-51D-30-NA",                               -- WWII Assets
  QF_4E = "QF-4E",
  RQ_1A_Predator = "RQ-1A Predator",
  S_3B = "S-3B",                                             -- Heavy Metal
  S_3B_Tanker = "S-3B Tanker",                               -- Heavy Metal
  SpitfireLFMkIX = "SpitfireLFMkIX",                         -- WWII Assets
  SpitfireLFMkIXCW = "SpitfireLFMkIXCW",                     -- WWII Assets
  Su_17M4 = "Su-17M4",
  Su_24M = "Su-24M",
  Su_24MR = "Su-24MR",
  Su_25 = "Su-25",
  Su_25T = "Su-25T",
  Su_25TM = "Su-25TM",
  Su_27 = "Su-27",
  Su_30 = "Su-30",
  Su_33 = "Su-33",
  Su_34 = "Su-34",
  TF_51D = "TF-51D",
  Tornado_GR4 = "Tornado GR4",
  Tornado_IDS = "Tornado IDS",
  Tu_142 = "Tu-142",
  Tu_160 = "Tu-160",
  Tu_22M3 = "Tu-22M3",
  Tu_95MS = "Tu-95MS",                                       -- Currenthill Assets
  WingLoong_I = "WingLoong-I",                               -- China Asset Pack
  Yak_40 = "Yak-40",
  Yak_52 = "Yak-52",
}

sms.constants.units.ships = {
  carriers = {
    CVN_71 = "CVN_71",                                       -- Supercarrier
    CVN_72 = "CVN_72",                                       -- Supercarrier
    CVN_73 = "CVN_73",                                       -- Supercarrier
    CVN_75 = "CVN_75",                                       -- Supercarrier
    CV_1143_5 = "CV_1143_5",                                 -- TAVKR 1143
    Essex = "Essex",                                         -- WWII Assets
    Forrestal = "Forrestal",
    KUZNECOW = "KUZNECOW",
    LHA_Tarawa = "LHA_Tarawa",
    Stennis = "Stennis",                                     -- Supercarrier
    Type_071 = "Type_071",                                   -- China Asset Pack
    VINSON = "VINSON",
    ara_vdm = "ara_vdm",                                     -- South Atlantic Assets
    atconveyor = "atconveyor",                               -- South Atlantic Assets
    hms_invincible = "hms_invincible",                       -- South Atlantic Assets
  },
  civilian = {
    Dry_cargo_ship_1 = "Dry-cargo ship-1",
    Dry_cargo_ship_2 = "Dry-cargo ship-2",
    ELNYA = "ELNYA",
    HandyWind = "HandyWind",                                 -- Tech Weapon Pack
    HarborTug = "HarborTug",                                 -- South Atlantic Assets
    Seawise_Giant = "Seawise_Giant",                         -- Tech Weapon Pack
    Ship_Tilde_Supply = "Ship_Tilde_Supply",                 -- South Atlantic Assets
    ZWEZDNY = "ZWEZDNY",
  },
  submarines = {
    IMPROVED_KILO = "IMPROVED_KILO",
    KILO = "KILO",
    SOM = "SOM",
    Type_093 = "Type_093",                                   -- China Asset Pack
    Uboat_VIIC = "Uboat_VIIC",                               -- WWII Assets
    santafe = "santafe",                                     -- South Atlantic Assets
  },
  warships = {
    ALBATROS = "ALBATROS",                                   -- Currenthill Assets
    BDK_775 = "BDK-775",                                     -- Tech Weapon Pack
    CHAP_Project22160 = "CHAP_Project22160",                 -- Currenthill Assets
    CHAP_Project22160_TorM2KM = "CHAP_Project22160_TorM2KM", -- Currenthill Assets
    CastleClass_01 = "CastleClass_01",                       -- South Atlantic Assets
    Higgins_boat = "Higgins_boat",                           -- WWII Assets
    LST_Mk2 = "LST_Mk2",                                     -- WWII Assets
    La_Combattante_II = "La_Combattante_II",                 -- Tech Weapon Pack
    MOLNIYA = "MOLNIYA",
    MOSCOW = "MOSCOW",
    NEUSTRASH = "NEUSTRASH",
    PERRY = "PERRY",
    PIOTR = "PIOTR",
    REZKY = "REZKY",
    Schnellboot_type_S130 = "Schnellboot_type_S130",         -- WWII Assets
    TICONDEROG = "TICONDEROG",
    Type_021_1 = "Type_021_1",                               -- China Asset Pack
    Type_052B = "Type_052B",                                 -- China Asset Pack
    Type_052C = "Type_052C",                                 -- China Asset Pack
    Type_054A = "Type_054A",                                 -- China Asset Pack
    USS_Arleigh_Burke_IIa = "USS_Arleigh_Burke_IIa",         -- Supercarrier
    USS_Samuel_Chase = "USS_Samuel_Chase",                   -- WWII Assets
    leander_gun_achilles = "leander-gun-achilles",           -- South Atlantic Assets
    leander_gun_andromeda = "leander-gun-andromeda",         -- South Atlantic Assets
    leander_gun_ariadne = "leander-gun-ariadne",             -- South Atlantic Assets
    leander_gun_condell = "leander-gun-condell",             -- South Atlantic Assets
    leander_gun_lynch = "leander-gun-lynch",                 -- South Atlantic Assets
    speedboat = "speedboat",
  },
}

sms.constants.units.trains = {
  Boxcartrinity = "Boxcartrinity",                           -- Tech Weapon Pack
  Coach_a_passenger = "Coach a passenger",                   -- Railway Objects
  Coach_a_platform = "Coach a platform",                     -- Railway Objects
  Coach_a_tank_blue = "Coach a tank blue",                   -- Railway Objects
  Coach_a_tank_yellow = "Coach a tank yellow",               -- Railway Objects
  Coach_cargo = "Coach cargo",                               -- Railway Objects
  Coach_cargo_open = "Coach cargo open",                     -- Railway Objects
  DRG_Class_86 = "DRG_Class_86",                             -- WWII Assets
  DR_50Ton_Flat_Wagon = "DR_50Ton_Flat_Wagon",               -- WWII Assets
  ES44AH = "ES44AH",                                         -- Tech Weapon Pack
  Electric_locomotive = "Electric locomotive",               -- Railway Objects
  German_covered_wagon_G10 = "German_covered_wagon_G10",     -- WWII Assets
  German_tank_wagon = "German_tank_wagon",                   -- WWII Assets
  Locomotive = "Locomotive",                                 -- Railway Objects
  Tankcartrinity = "Tankcartrinity",                         -- Tech Weapon Pack
  Train = "Train",
  Wellcarnsc = "Wellcarnsc",                                 -- Tech Weapon Pack
}

sms.constants.units.unarmed = {
  AA8 = "AA8",                                               -- Tech Weapon Pack
  ATMZ_5 = "ATMZ-5",
  ATZ_10 = "ATZ-10",
  ATZ_5 = "ATZ-5",                                           -- Tech Weapon Pack
  ATZ_60_Maz = "ATZ-60_Maz",                                 -- Tech Weapon Pack
  B600_drivable = "B600_drivable",                           -- Massun92 Assets
  Bedford_MWD = "Bedford_MWD",                               -- Tech Weapon Pack
  Blitz_36_6700A = "Blitz_36-6700A",                         -- Tech Weapon Pack
  CCKW_353 = "CCKW_353",                                     -- WWII Assets
  CHAP_M1083 = "CHAP_M1083",                                 -- Currenthill Assets
  GAZ_3307 = "GAZ-3307",
  GAZ_3308 = "GAZ-3308",
  GAZ_66 = "GAZ-66",
  GD_20 = "GD-20",                                           -- China Asset Pack
  GPS_Spoofer_Blue = "GPS_Spoofer_Blue",                     -- Tech Weapon Pack
  GPS_Spoofer_Red = "GPS_Spoofer_Red",                       -- Tech Weapon Pack
  HEMTT_TFFT = "HEMTT TFFT",
  Horch_901_typ_40_kfz_21 = "Horch_901_typ_40_kfz_21",       -- WWII Assets
  Hummer = "Hummer",
  IKARUS_Bus = "IKARUS Bus",
  KAMAZ_Truck = "KAMAZ Truck",
  KrAZ6322 = "KrAZ6322",
  Kubelwagen_82 = "Kubelwagen_82",                           -- WWII Assets
  LARC_V = "LARC-V",                                         -- South Atlantic Assets
  LAZ_Bus = "LAZ Bus",
  Land_Rover_101_FC = "Land_Rover_101_FC",                   -- Tech Weapon Pack
  Land_Rover_109_S3 = "Land_Rover_109_S3",                   -- Tech Weapon Pack
  LiAZ_Bus = "LiAZ Bus",
  M30_CC = "M30_CC",                                         -- WWII Assets
  M978_HEMTT_Tanker = "M978 HEMTT Tanker",
  MAZ_6303 = "MAZ-6303",
  MJ_1_drivable = "MJ-1_drivable",                           -- Massun92 Assets
  M_818 = "M 818",
  P20_drivable = "P20_drivable",                             -- Massun92 Assets
  Predator_GCS = "Predator GCS",
  Predator_TrojanSpirit = "Predator TrojanSpirit",
  SKP_11 = "SKP-11",
  S_75_ZIL = "S_75_ZIL",                                     -- Tech Weapon Pack
  Sd_Kfz_2 = "Sd_Kfz_2",                                     -- WWII Assets
  Sd_Kfz_7 = "Sd_Kfz_7",                                     -- WWII Assets
  Suidae = "Suidae",
  TZ_22_KrAZ = "TZ-22_KrAZ",                                 -- Tech Weapon Pack
  Tigr_233036 = "Tigr_233036",
  Trolley_bus = "Trolley bus",
  TugHarlan_drivable = "TugHarlan_drivable",                 -- Massun92 Assets
  Type_94_Truck = "Type_94_Truck",                           -- WWII Assets
  Type_98_So_Da = "Type_98_So_Da",                           -- WWII Assets
  UAZ_469 = "UAZ-469",
  Ural_375 = "Ural-375",
  Ural_375_PBU = "Ural-375 PBU",
  Ural_4320T = "Ural-4320T",
  Ural_4320_31 = "Ural-4320-31",
  Ural_4320_APA_5D = "Ural-4320 APA-5D",
  Ural_ATsP_6 = "Ural ATsP-6",
  VAZ_Car = "VAZ Car",
  Willys_MB = "Willys_MB",                                   -- WWII Assets
  ZIL_131_KUNG = "ZIL-131 KUNG",
  ZIL_135 = "ZIL-135",                                       -- Tech Weapon Pack
  ZIL_4331 = "ZIL-4331",
  ZiL_131_APA_80 = "ZiL-131 APA-80",
  gaz_66_civil = "gaz-66_civil",                             -- Tech Weapon Pack
  kamaz_tent_civil = "kamaz_tent_civil",                     -- Tech Weapon Pack
  prmg_gp_beacon = "prmg_gp_beacon",                         -- Tech Weapon Pack
  prmg_loc_beacon = "prmg_loc_beacon",                       -- Tech Weapon Pack
  r11_volvo_drivable = "r11_volvo_drivable",                 -- Massun92 Assets
  rsbn_beacon = "rsbn_beacon",                               -- Tech Weapon Pack
  tacr2a = "tacr2a",                                         -- South Atlantic Assets
  ural_4230_civil_b = "ural_4230_civil_b",                   -- Tech Weapon Pack
  ural_4230_civil_t = "ural_4230_civil_t",                   -- Tech Weapon Pack
  ural_atz5_civil = "ural_atz5_civil",                       -- Tech Weapon Pack
  zil_131_civil = "zil-131_civil",                           -- Tech Weapon Pack
}

-- ============================================================
-- Origin lookup
-- ============================================================

local _origin = {
  ["A-20G"] = "WWII Assets",
  ["AA8"] = "Tech Weapon Pack",
  ["ALBATROS"] = "Currenthill Assets",
  ["ATZ-5"] = "Tech Weapon Pack",
  ["ATZ-60_Maz"] = "Tech Weapon Pack",
  ["Allies_Director"] = "WWII Assets",
  ["B-17G"] = "WWII Assets",
  ["B-1B"] = "Heavy Metal",
  ["B-52H"] = "Heavy Metal",
  ["B600_drivable"] = "Massun92 Assets",
  ["BDK-775"] = "Tech Weapon Pack",
  ["BRDM-2"] = "Cold War Asset Pack",
  ["BRDM-2_malyutka"] = "Cold War Asset Pack",
  ["BTR-60"] = "Cold War Asset Pack",
  ["BTR-70"] = "Cold War Asset Pack",
  ["BTR-80"] = "Tech Weapon Pack",
  ["BTR-82A"] = "Tech Weapon Pack",
  ["Bedford_MWD"] = "Tech Weapon Pack",
  ["Bf-109K-4"] = "WWII Assets",
  ["Blitz_36-6700A"] = "Tech Weapon Pack",
  ["Boxcartrinity"] = "Tech Weapon Pack",
  ["C-130J-30"] = "C-130 Assets",
  ["C-47"] = "WWII Assets",
  ["CCKW_353"] = "WWII Assets",
  ["CHAP_9K720_Cluster"] = "Currenthill Assets",
  ["CHAP_9K720_HE"] = "Currenthill Assets",
  ["CHAP_BMPT"] = "Currenthill Assets",
  ["CHAP_FV101"] = "Currenthill Assets",
  ["CHAP_FV107"] = "Currenthill Assets",
  ["CHAP_IRISTSLM_CP"] = "Currenthill Assets",
  ["CHAP_IRISTSLM_LN"] = "Currenthill Assets",
  ["CHAP_IRISTSLM_STR"] = "Currenthill Assets",
  ["CHAP_M1083"] = "Currenthill Assets",
  ["CHAP_M1130"] = "Currenthill Assets",
  ["CHAP_M142_ATACMS_M39A1"] = "Currenthill Assets",
  ["CHAP_M142_ATACMS_M48"] = "Currenthill Assets",
  ["CHAP_M142_GMLRS_M30"] = "Currenthill Assets",
  ["CHAP_M142_GMLRS_M31"] = "Currenthill Assets",
  ["CHAP_MATV"] = "Currenthill Assets",
  ["CHAP_PantsirS1"] = "Currenthill Assets",
  ["CHAP_Project22160"] = "Currenthill Assets",
  ["CHAP_Project22160_TorM2KM"] = "Currenthill Assets",
  ["CHAP_T64BV"] = "Currenthill Assets",
  ["CHAP_T84OplotM"] = "Currenthill Assets",
  ["CHAP_T90M"] = "Currenthill Assets",
  ["CHAP_TOS1A"] = "Currenthill Assets",
  ["CHAP_TigerUHT"] = "Currenthill Assets",
  ["CHAP_TorM2"] = "Currenthill Assets",
  ["CVN_71"] = "Supercarrier",
  ["CVN_72"] = "Supercarrier",
  ["CVN_73"] = "Supercarrier",
  ["CVN_75"] = "Supercarrier",
  ["CV_1143_5"] = "TAVKR 1143",
  ["CastleClass_01"] = "South Atlantic Assets",
  ["Centaur_IV"] = "WWII Assets",
  ["Chieftain_mk3"] = "Tech Weapon Pack",
  ["Churchill_VII"] = "WWII Assets",
  ["Coach a passenger"] = "Railway Objects",
  ["Coach a platform"] = "Railway Objects",
  ["Coach a tank blue"] = "Railway Objects",
  ["Coach a tank yellow"] = "Railway Objects",
  ["Coach cargo"] = "Railway Objects",
  ["Coach cargo open"] = "Railway Objects",
  ["Cromwell_IV"] = "WWII Assets",
  ["DRG_Class_86"] = "WWII Assets",
  ["DR_50Ton_Flat_Wagon"] = "WWII Assets",
  ["Daimler_AC"] = "WWII Assets",
  ["ES44AH"] = "Tech Weapon Pack",
  ["Electric locomotive"] = "Railway Objects",
  ["Elefant_SdKfz_184"] = "WWII Assets",
  ["Essex"] = "WWII Assets",
  ["FPS-117"] = "Tech Weapon Pack",
  ["FPS-117 Dome"] = "Tech Weapon Pack",
  ["FPS-117 ECS"] = "Tech Weapon Pack",
  ["FW-190A8"] = "WWII Assets",
  ["FW-190D9"] = "WWII Assets",
  ["Falcon_Gyrocopter"] = "China Asset Pack",
  ["Flakscheinwerfer_37"] = "WWII Assets",
  ["FuMG-401"] = "WWII Assets",
  ["FuSe-65"] = "WWII Assets",
  ["GD-20"] = "China Asset Pack",
  ["GPS_Spoofer_Blue"] = "Tech Weapon Pack",
  ["GPS_Spoofer_Red"] = "Tech Weapon Pack",
  ["German_covered_wagon_G10"] = "WWII Assets",
  ["German_tank_wagon"] = "WWII Assets",
  ["H-6J"] = "China Asset Pack",
  ["HEMTT_C-RAM_Phalanx"] = "Heavy Metal",
  ["HL_B8M1"] = "Tech Weapon Pack",
  ["HL_DSHK"] = "Tech Weapon Pack",
  ["HL_KORD"] = "Tech Weapon Pack",
  ["HL_ZU-23"] = "Tech Weapon Pack",
  ["HQ-7_LN_P"] = "China Asset Pack",
  ["HQ-7_LN_SP"] = "China Asset Pack",
  ["HQ-7_STR_SP"] = "China Asset Pack",
  ["HandyWind"] = "Tech Weapon Pack",
  ["HarborTug"] = "South Atlantic Assets",
  ["Higgins_boat"] = "WWII Assets",
  ["Horch_901_typ_40_kfz_21"] = "WWII Assets",
  ["J-11A"] = "China Asset Pack",
  ["JF-17"] = "China Asset Pack",
  ["JagdPz_IV"] = "WWII Assets",
  ["Jagdpanther_G1"] = "WWII Assets",
  ["Ju-88A4"] = "WWII Assets",
  ["KDO_Mod40"] = "WWII Assets",
  ["KJ-2000"] = "China Asset Pack",
  ["KS-19"] = "Tech Weapon Pack",
  ["Kubelwagen_82"] = "WWII Assets",
  ["L118_Unit"] = "South Atlantic Assets",
  ["LARC-V"] = "South Atlantic Assets",
  ["LST_Mk2"] = "WWII Assets",
  ["La_Combattante_II"] = "Tech Weapon Pack",
  ["Land_Rover_101_FC"] = "Tech Weapon Pack",
  ["Land_Rover_109_S3"] = "Tech Weapon Pack",
  ["LeFH_18-40-105"] = "WWII Assets",
  ["Leopard-2"] = "Tech Weapon Pack",
  ["Leopard-2A5"] = "Tech Weapon Pack",
  ["Locomotive"] = "Railway Objects",
  ["M-1 Abrams"] = "Heavy Metal",
  ["M10_GMC"] = "WWII Assets",
  ["M12_GMC"] = "WWII Assets",
  ["M1A2C_SEP_V3"] = "Heavy Metal",
  ["M1_37mm"] = "WWII Assets",
  ["M2A1-105"] = "WWII Assets",
  ["M2A1_halftrack"] = "Tech Weapon Pack",
  ["M30_CC"] = "WWII Assets",
  ["M45_Quadmount"] = "WWII Assets",
  ["M4A4_Sherman_FF"] = "WWII Assets",
  ["M4_Sherman"] = "Tech Weapon Pack",
  ["M4_Tractor"] = "WWII Assets",
  ["M8_Greyhound"] = "WWII Assets",
  ["MJ-1_drivable"] = "Massun92 Assets",
  ["Maschinensatz_33"] = "WWII Assets",
  ["MaxxPro_MRAP"] = "Heavy Metal",
  ["Mi-28N"] = "Currenthill Assets",
  ["Mirage-F1AD"] = "Mirage F1 Assets",
  ["Mirage-F1AZ"] = "Mirage F1 Assets",
  ["Mirage-F1B"] = "Mirage F1 Assets",
  ["Mirage-F1BD"] = "Mirage F1 Assets",
  ["Mirage-F1BE"] = "Mirage F1 Assets",
  ["Mirage-F1BQ"] = "Mirage F1 Assets",
  ["Mirage-F1C"] = "Mirage F1 Assets",
  ["Mirage-F1C-200"] = "Mirage F1 Assets",
  ["Mirage-F1CE"] = "Mirage F1 Assets",
  ["Mirage-F1CG"] = "Mirage F1 Assets",
  ["Mirage-F1CH"] = "Mirage F1 Assets",
  ["Mirage-F1CJ"] = "Mirage F1 Assets",
  ["Mirage-F1CK"] = "Mirage F1 Assets",
  ["Mirage-F1CR"] = "Mirage F1 Assets",
  ["Mirage-F1CT"] = "Mirage F1 Assets",
  ["Mirage-F1CZ"] = "Mirage F1 Assets",
  ["Mirage-F1DDA"] = "Mirage F1 Assets",
  ["Mirage-F1ED"] = "Mirage F1 Assets",
  ["Mirage-F1EDA"] = "Mirage F1 Assets",
  ["Mirage-F1EE"] = "Mirage F1 Assets",
  ["Mirage-F1EH"] = "Mirage F1 Assets",
  ["Mirage-F1EQ"] = "Mirage F1 Assets",
  ["Mirage-F1JA"] = "Mirage F1 Assets",
  ["Mirage-F1M-CE"] = "Mirage F1 Assets",
  ["Mirage-F1M-EE"] = "Mirage F1 Assets",
  ["MosquitoFBMkVI"] = "WWII Assets",
  ["NASAMS_Command_Post"] = "Tech Weapon Pack",
  ["NASAMS_LN_B"] = "Tech Weapon Pack",
  ["NASAMS_LN_C"] = "Tech Weapon Pack",
  ["NASAMS_Radar_MPQ64F1"] = "Tech Weapon Pack",
  ["P-47D-30"] = "WWII Assets",
  ["P-47D-30bl1"] = "WWII Assets",
  ["P-47D-40"] = "WWII Assets",
  ["P-51D"] = "WWII Assets",
  ["P-51D-30-NA"] = "WWII Assets",
  ["P14_SR"] = "Cold War Asset Pack",
  ["P20_drivable"] = "Massun92 Assets",
  ["PL5EII Loadout"] = "China Asset Pack",
  ["PL8 Loadout"] = "China Asset Pack",
  ["PLZ05"] = "China Asset Pack",
  ["PT_76"] = "Tech Weapon Pack",
  ["Pak40"] = "WWII Assets",
  ["Pz_IV_H"] = "Tech Weapon Pack",
  ["Pz_V_Panther_G"] = "WWII Assets",
  ["QF_37_AA"] = "WWII Assets",
  ["RD_75"] = "Tech Weapon Pack",
  ["RLS_19J6"] = "Tech Weapon Pack",
  ["RPC_5N62V"] = "Tech Weapon Pack",
  ["S-200_Launcher"] = "Tech Weapon Pack",
  ["S-300PS 40B6M tr"] = "Heavy Metal",
  ["S-300PS 40B6MD sr"] = "Heavy Metal",
  ["S-300PS 40B6MD sr_19J6"] = "Heavy Metal",
  ["S-300PS 54K6 cp"] = "Heavy Metal",
  ["S-300PS 5H63C 30H6_tr"] = "Heavy Metal",
  ["S-300PS 5P85C ln"] = "Heavy Metal",
  ["S-300PS 5P85D ln"] = "Heavy Metal",
  ["S-300PS 64H6E sr"] = "Heavy Metal",
  ["S-3B"] = "Heavy Metal",
  ["S-3B Tanker"] = "Heavy Metal",
  ["S-60_Type59_Artillery"] = "Tech Weapon Pack",
  ["SD10 Loadout"] = "China Asset Pack",
  ["SK_C_28_naval_gun"] = "WWII Assets",
  ["SNR_75V"] = "Tech Weapon Pack",
  ["SON_9"] = "Tech Weapon Pack",
  ["S_75M_Volhov"] = "Tech Weapon Pack",
  ["S_75_ZIL"] = "Tech Weapon Pack",
  ["Schnellboot_type_S130"] = "WWII Assets",
  ["Scud_B"] = "Tech Weapon Pack",
  ["Sd_Kfz_2"] = "WWII Assets",
  ["Sd_Kfz_234_2_Puma"] = "WWII Assets",
  ["Sd_Kfz_251"] = "Tech Weapon Pack",
  ["Sd_Kfz_7"] = "WWII Assets",
  ["Seawise_Giant"] = "Tech Weapon Pack",
  ["Ship_Tilde_Supply"] = "South Atlantic Assets",
  ["Silkworm_SR"] = "Tech Weapon Pack",
  ["SpitfireLFMkIX"] = "WWII Assets",
  ["SpitfireLFMkIXCW"] = "WWII Assets",
  ["Stennis"] = "Supercarrier",
  ["Strela-1 9P31"] = "Cold War Asset Pack",
  ["Stug_III"] = "WWII Assets",
  ["Stug_IV"] = "WWII Assets",
  ["SturmPzIV"] = "WWII Assets",
  ["T-34-85"] = "Cold War Asset Pack",
  ["T-72B3"] = "Tech Weapon Pack",
  ["T-80B"] = "Cold War Asset Pack",
  ["T-90"] = "Currenthill Assets",
  ["T155_Firtina"] = "Tech Weapon Pack",
  ["T62M"] = "Cold War Asset Pack",
  ["TYPE-59"] = "China Asset Pack",
  ["TZ-22_KrAZ"] = "Tech Weapon Pack",
  ["Tankcartrinity"] = "Tech Weapon Pack",
  ["Tetrarch"] = "WWII Assets",
  ["Tiger_I"] = "WWII Assets",
  ["Tiger_II_H"] = "WWII Assets",
  ["Tu-95MS"] = "Currenthill Assets",
  ["TugHarlan_drivable"] = "Massun92 Assets",
  ["Type_021_1"] = "China Asset Pack",
  ["Type_052B"] = "China Asset Pack",
  ["Type_052C"] = "China Asset Pack",
  ["Type_054A"] = "China Asset Pack",
  ["Type_071"] = "China Asset Pack",
  ["Type_093"] = "China Asset Pack",
  ["Type_3_80mm_AA"] = "WWII Assets",
  ["Type_88_75mm_AA"] = "WWII Assets",
  ["Type_89_I_Go"] = "WWII Assets",
  ["Type_94_25mm_AA_Truck"] = "WWII Assets",
  ["Type_94_Truck"] = "WWII Assets",
  ["Type_96_25mm_AA"] = "WWII Assets",
  ["Type_98_Ke_Ni"] = "WWII Assets",
  ["Type_98_So_Da"] = "WWII Assets",
  ["USS_Arleigh_Burke_IIa"] = "Supercarrier",
  ["USS_Samuel_Chase"] = "WWII Assets",
  ["Uboat_VIIC"] = "WWII Assets",
  ["VAB_Mephisto"] = "Tech Weapon Pack",
  ["Wellcarnsc"] = "Tech Weapon Pack",
  ["Wespe124"] = "WWII Assets",
  ["Willys_MB"] = "WWII Assets",
  ["WingLoong-I"] = "China Asset Pack",
  ["ZBD04A"] = "China Asset Pack",
  ["ZIL-135"] = "Tech Weapon Pack",
  ["ZSU_57_2"] = "Tech Weapon Pack",
  ["ZTZ96B"] = "China Asset Pack",
  ["ara_vdm"] = "South Atlantic Assets",
  ["atconveyor"] = "South Atlantic Assets",
  ["bofors40"] = "Tech Weapon Pack",
  ["fire_control"] = "WWII Assets",
  ["flak18"] = "Tech Weapon Pack",
  ["flak30"] = "WWII Assets",
  ["flak36"] = "WWII Assets",
  ["flak37"] = "WWII Assets",
  ["flak38"] = "WWII Assets",
  ["flak41"] = "WWII Assets",
  ["gaz-66_civil"] = "Tech Weapon Pack",
  ["generator_5i57"] = "Tech Weapon Pack",
  ["hms_invincible"] = "South Atlantic Assets",
  ["hy_launcher"] = "Tech Weapon Pack",
  ["kamaz_tent_civil"] = "Tech Weapon Pack",
  ["leander-gun-achilles"] = "South Atlantic Assets",
  ["leander-gun-andromeda"] = "South Atlantic Assets",
  ["leander-gun-ariadne"] = "South Atlantic Assets",
  ["leander-gun-condell"] = "South Atlantic Assets",
  ["leander-gun-lynch"] = "South Atlantic Assets",
  ["leopard-2A4"] = "Tech Weapon Pack",
  ["leopard-2A4_trs"] = "Tech Weapon Pack",
  ["prmg_gp_beacon"] = "Tech Weapon Pack",
  ["prmg_loc_beacon"] = "Tech Weapon Pack",
  ["r11_volvo_drivable"] = "Massun92 Assets",
  ["rapier_fsa_blindfire_radar"] = "Tech Weapon Pack",
  ["rapier_fsa_launcher"] = "Tech Weapon Pack",
  ["rapier_fsa_optical_tracker_unit"] = "Tech Weapon Pack",
  ["rsbn_beacon"] = "Tech Weapon Pack",
  ["santafe"] = "South Atlantic Assets",
  ["soldier_mauser98"] = "WWII Assets",
  ["soldier_wwii_br_01"] = "WWII Assets",
  ["soldier_wwii_us"] = "WWII Assets",
  ["tacr2a"] = "South Atlantic Assets",
  ["tt_B8M1"] = "Tech Weapon Pack",
  ["tt_DSHK"] = "Tech Weapon Pack",
  ["tt_KORD"] = "Tech Weapon Pack",
  ["tt_ZU-23"] = "Tech Weapon Pack",
  ["ural_4230_civil_b"] = "Tech Weapon Pack",
  ["ural_4230_civil_t"] = "Tech Weapon Pack",
  ["ural_atz5_civil"] = "Tech Weapon Pack",
  ["v1_launcher"] = "WWII Assets",
  ["zil-131_civil"] = "Tech Weapon Pack",
}

---@param type_string string  DCS type-string to look up
---@return string|nil  asset-pack label if non-base, nil otherwise
sms.constants.units.origin_of = function(type_string)
  if type(type_string) ~= "string" then return nil end
  return _origin[type_string]
end
