package main

import (
	"flag"
	"fmt"
	"io"
)

// commandFunc is the signature for every subcommand. It receives the args
// after the subcommand name (so for `dcs-sms exec --file foo.lua`,
// argsAfterCmd would be ["--file", "foo.lua"]). It returns an OS exit code.
type commandFunc func(argsAfterCmd []string, stdout, stderr io.Writer) int

// cmdInfo carries everything the dispatcher and the doc generator need
// about one subcommand. Flags and Synopsis are optional; when both are
// non-empty, the command is included in the autogenerated reference docs
// at docs/cli/. When Flags is nil OR Synopsis == "" the command is treated
// as hidden by the doc generator.
type cmdInfo struct {
	Run      commandFunc
	Flags    func() *flag.FlagSet
	Synopsis string
	Examples []string // TODO(#49 doc gen): consumed by `dcs-sms doc` once Task 10 lands
}

// commands maps subcommand names to their metadata. Subcommands register
// themselves here in init() blocks across cmd/dcs-sms/*.go.
var commands = map[string]cmdInfo{}

// registerInfo registers a command with full metadata (the new canonical API).
func registerInfo(name string, info cmdInfo) {
	if info.Run == nil {
		panic("registerInfo: Run is required for " + name)
	}
	if _, exists := commands[name]; exists {
		panic("duplicate command registration: " + name)
	}
	commands[name] = info
}

// register is a backward-compatible wrapper for the old (name, fn) API.
// Prefer registerInfo for new code; this exists so the migration to the
// doc-aware registry can land incrementally per namespace.
func register(name string, fn commandFunc) {
	registerInfo(name, cmdInfo{Run: fn})
}

// flagsOnly adapts a flags-builder of the form `func() (*flag.FlagSet, *Opts)`
// to the `func() *flag.FlagSet` shape that cmdInfo.Flags expects. The doc
// generator only needs the FlagSet; the opts pointer is for the run handler.
//
// Use as: registerInfo("foo", cmdInfo{ ..., Flags: flagsOnly(fooFlags), ... })
func flagsOnly[T any](b func() (*flag.FlagSet, T)) func() *flag.FlagSet {
	return func() *flag.FlagSet {
		fs, _ := b()
		return fs
	}
}

// dispatch routes args[0] (subcommand name) to its handler. Pure function
// (returns exit code, writes to provided writers) so it's trivially
// testable without touching os.Exit / os.Stdout.
func dispatch(args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		printUsage(stderr)
		return 2
	}
	switch args[0] {
	case "--version", "-v", "version":
		fmt.Fprintln(stdout, version)
		return 0
	case "--help", "-h", "help":
		printUsage(stdout)
		return 0
	}
	cmd, ok := commands[args[0]]
	if !ok {
		fmt.Fprintf(stderr, "dcs-sms: unknown command %q\n", args[0])
		printUsage(stderr)
		return 2
	}
	return cmd.Run(args[1:], stdout, stderr)
}

func printUsage(w io.Writer) {
	fmt.Fprintln(w, "dcs-sms — Digital Combat Simulator scripting bridge")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Usage: dcs-sms <command> [flags]")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Commands:")
	fmt.Fprintln(w, "  exec          execute a Lua snippet (use --target mission|gui|auto, default auto)")
	fmt.Fprintln(w, "  me            Mission Editor commands (run `dcs-sms me --help` for the verb list)")
	fmt.Fprintln(w, "  status        report whether the hook is alive and a mission is loaded")
	fmt.Fprintln(w, "  screenshot    capture the DCS window to a PNG (Windows only)")
	fmt.Fprintln(w, "  tail-log      read recent lines from dcs.log")
	fmt.Fprintln(w, "  install-hook  install/update the Lua hook in Saved Games/DCS*/Scripts/Hooks/")
	fmt.Fprintln(w, "  install-me-mod   install/update the Mission Editor mod into <DCS install>/MissionEditor/")
	fmt.Fprintln(w, "  uninstall-me-mod remove the Mission Editor mod (revert MissionEditor.lua, delete modules)")
	fmt.Fprintln(w, "  gen-units     regenerate framework/constants/{units,statics}.lua from dcs-lua-datamine")
	fmt.Fprintln(w, "  update        download the latest dcs-sms.exe from GitHub and replace this binary")
	fmt.Fprintln(w, "  doc           regenerate docs/cli/ — per-command markdown reference + index")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Run `dcs-sms <command> --help` for command-specific flags.")
}
