package main

import (
	"flag"
	"fmt"
	"io"
	"time"
)

func init() {
	registerMe("drawing", "get", meDrawingGetCmd)
}

// meDrawingGetCmd implements `dcs-sms me drawing get --name <X>`.
//
// Returns the full drawing structure (primitiveType, polygonMode,
// shape-specific fields, color, layer, etc.) plus translated --north /
// --east. mapId and mapData are stripped — mapId is a render-side
// handle and mapData is regenerated by loadFromMission from the
// on-disk fields, so neither belongs in the writable surface.
func meDrawingGetCmd(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("me drawing get", flag.ContinueOnError)
	fs.SetOutput(stderr)
	var (
		flagName       = fs.String("name", "", "drawing name")
		flagTimeout    = fs.Duration("timeout", 30*time.Second, "wall-clock timeout")
		flagPretty     = fs.Bool("pretty", false, "indent JSON output")
		flagSavedGames = fs.String("saved-games", "", "override Saved Games path")
	)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *flagName == "" {
		fmt.Fprintln(stderr, "dcs-sms me drawing get: --name is required")
		return 2
	}
	luaArgs := fmt.Sprintf("{ name = %q }", *flagName)

	resp, exitCode := runMeVerb("drawing_get", luaArgs, *flagTimeout, *flagSavedGames, stderr)
	if exitCode != 0 {
		return exitCode
	}
	return emitMeResponse(resp, *flagPretty, stdout)
}
